// <auto-generated>
/*
 * LoginRadius API
 *
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LoginRadius.Sdk.Internal.OpenApi.Client;

namespace LoginRadius.Sdk.Internal.OpenApi.Model
{
    /// <summary>
    /// ActiveSessionResponse
    /// </summary>
    public partial class ActiveSessionResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ActiveSessionResponse" /> class.
        /// </summary>
        /// <param name="nextCursor">nextCursor</param>
        /// <param name="data">data</param>
        [JsonConstructor]
        public ActiveSessionResponse(Option<int?> nextCursor = default, Option<List<ActiveSession>?> data = default)
        {
            NextCursorOption = nextCursor;
            DataOption = data;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of NextCursor
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> NextCursorOption { get; private set; }

        /// <summary>
        /// Gets or Sets NextCursor
        /// </summary>
        [JsonPropertyName("nextCursor")]
        public int? NextCursor { get { return this.NextCursorOption; } set { this.NextCursorOption = new(value); } }

        /// <summary>
        /// Used to track the state of Data
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<ActiveSession>?> DataOption { get; private set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [JsonPropertyName("data")]
        public List<ActiveSession>? Data { get { return this.DataOption; } set { this.DataOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ActiveSessionResponse {\n");
            sb.Append("  NextCursor: ").Append(NextCursor).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ActiveSessionResponse" />
    /// </summary>
    public class ActiveSessionResponseJsonConverter : JsonConverter<ActiveSessionResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="ActiveSessionResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ActiveSessionResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> nextCursor = default;
            Option<List<ActiveSession>?> data = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "nextCursor":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                nextCursor = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "data":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                data = new Option<List<ActiveSession>?>(JsonSerializer.Deserialize<List<ActiveSession>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (nextCursor.IsSet && nextCursor.Value == null)
                throw new ArgumentNullException(nameof(nextCursor), "Property is not nullable for class ActiveSessionResponse.");

            if (data.IsSet && data.Value == null)
                throw new ArgumentNullException(nameof(data), "Property is not nullable for class ActiveSessionResponse.");

            return new ActiveSessionResponse(nextCursor, data);
        }

        /// <summary>
        /// Serializes a <see cref="ActiveSessionResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="activeSessionResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ActiveSessionResponse activeSessionResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, activeSessionResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ActiveSessionResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="activeSessionResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ActiveSessionResponse activeSessionResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (activeSessionResponse.DataOption.IsSet && activeSessionResponse.Data == null)
                throw new ArgumentNullException(nameof(activeSessionResponse.Data), "Property is required for class ActiveSessionResponse.");

            if (activeSessionResponse.NextCursorOption.IsSet)
                writer.WriteNumber("nextCursor", activeSessionResponse.NextCursorOption.Value!.Value);

            if (activeSessionResponse.DataOption.IsSet)
            {
                writer.WritePropertyName("data");
                JsonSerializer.Serialize(writer, activeSessionResponse.Data, jsonSerializerOptions);
            }
        }
    }
}
