// <auto-generated>
/*
 * LoginRadius API
 *
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LoginRadius.Sdk.Internal.OpenApi.Client;

namespace LoginRadius.Sdk.Internal.OpenApi.Model
{
    /// <summary>
    /// Response object returned to initiate Passkey login (WebAuthn)
    /// </summary>
    public partial class BeginPasskeyMFAVerification200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BeginPasskeyMFAVerification200Response" /> class.
        /// </summary>
        /// <param name="loginBeginCredential">loginBeginCredential</param>
        [JsonConstructor]
        public BeginPasskeyMFAVerification200Response(Option<BeginPasskeyMFAVerification200ResponseLoginBeginCredential?> loginBeginCredential = default)
        {
            LoginBeginCredentialOption = loginBeginCredential;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of LoginBeginCredential
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<BeginPasskeyMFAVerification200ResponseLoginBeginCredential?> LoginBeginCredentialOption { get; private set; }

        /// <summary>
        /// Gets or Sets LoginBeginCredential
        /// </summary>
        [JsonPropertyName("LoginBeginCredential")]
        public BeginPasskeyMFAVerification200ResponseLoginBeginCredential? LoginBeginCredential { get { return this.LoginBeginCredentialOption; } set { this.LoginBeginCredentialOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BeginPasskeyMFAVerification200Response {\n");
            sb.Append("  LoginBeginCredential: ").Append(LoginBeginCredential).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BeginPasskeyMFAVerification200Response" />
    /// </summary>
    public class BeginPasskeyMFAVerification200ResponseJsonConverter : JsonConverter<BeginPasskeyMFAVerification200Response>
    {
        /// <summary>
        /// Deserializes json to <see cref="BeginPasskeyMFAVerification200Response" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override BeginPasskeyMFAVerification200Response Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<BeginPasskeyMFAVerification200ResponseLoginBeginCredential?> loginBeginCredential = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "LoginBeginCredential":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                loginBeginCredential = new Option<BeginPasskeyMFAVerification200ResponseLoginBeginCredential?>(JsonSerializer.Deserialize<BeginPasskeyMFAVerification200ResponseLoginBeginCredential>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (loginBeginCredential.IsSet && loginBeginCredential.Value == null)
                throw new ArgumentNullException(nameof(loginBeginCredential), "Property is not nullable for class BeginPasskeyMFAVerification200Response.");

            return new BeginPasskeyMFAVerification200Response(loginBeginCredential);
        }

        /// <summary>
        /// Serializes a <see cref="BeginPasskeyMFAVerification200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="beginPasskeyMFAVerification200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, BeginPasskeyMFAVerification200Response beginPasskeyMFAVerification200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, beginPasskeyMFAVerification200Response, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="BeginPasskeyMFAVerification200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="beginPasskeyMFAVerification200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, BeginPasskeyMFAVerification200Response beginPasskeyMFAVerification200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            if (beginPasskeyMFAVerification200Response.LoginBeginCredentialOption.IsSet && beginPasskeyMFAVerification200Response.LoginBeginCredential == null)
                throw new ArgumentNullException(nameof(beginPasskeyMFAVerification200Response.LoginBeginCredential), "Property is required for class BeginPasskeyMFAVerification200Response.");

            if (beginPasskeyMFAVerification200Response.LoginBeginCredentialOption.IsSet)
            {
                writer.WritePropertyName("LoginBeginCredential");
                JsonSerializer.Serialize(writer, beginPasskeyMFAVerification200Response.LoginBeginCredential, jsonSerializerOptions);
            }
        }
    }
}
