// <auto-generated>
/*
 * LoginRadius API
 *
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LoginRadius.Sdk.Internal.OpenApi.Client;

namespace LoginRadius.Sdk.Internal.OpenApi.Model
{
    /// <summary>
    /// ConsentOptionModel
    /// </summary>
    public partial class ConsentOptionModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConsentOptionModel" /> class.
        /// </summary>
        /// <param name="title">Title of the consent option.</param>
        /// <param name="description">Description of the consent option.</param>
        [JsonConstructor]
        public ConsentOptionModel(Option<string?> title = default, Option<string?> description = default)
        {
            TitleOption = title;
            DescriptionOption = description;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Title
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TitleOption { get; private set; }

        /// <summary>
        /// Title of the consent option.
        /// </summary>
        /// <value>Title of the consent option.</value>
        /* <example>SMS Consent</example> */
        [JsonPropertyName("Title")]
        public string? Title { get { return this.TitleOption; } set { this.TitleOption = new(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Description of the consent option.
        /// </summary>
        /// <value>Description of the consent option.</value>
        /* <example>Consent to receive SMS notifications</example> */
        [JsonPropertyName("Description")]
        public string? Description { get { return this.DescriptionOption; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ConsentOptionModel {\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Title (string) maxLength
            if (this.Title != null && this.Title.Length > 150)
            {
                yield return new ValidationResult("Invalid value for Title, length must be less than 150.", new [] { "Title" });
            }

            // Description (string) maxLength
            if (this.Description != null && this.Description.Length > 1000)
            {
                yield return new ValidationResult("Invalid value for Description, length must be less than 1000.", new [] { "Description" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ConsentOptionModel" />
    /// </summary>
    public class ConsentOptionModelJsonConverter : JsonConverter<ConsentOptionModel>
    {
        /// <summary>
        /// Deserializes json to <see cref="ConsentOptionModel" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ConsentOptionModel Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> title = default;
            Option<string?> description = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "Title":
                            title = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "Description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (title.IsSet && title.Value == null)
                throw new ArgumentNullException(nameof(title), "Property is not nullable for class ConsentOptionModel.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class ConsentOptionModel.");

            return new ConsentOptionModel(title, description);
        }

        /// <summary>
        /// Serializes a <see cref="ConsentOptionModel" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="consentOptionModel"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ConsentOptionModel consentOptionModel, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, consentOptionModel, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ConsentOptionModel" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="consentOptionModel"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ConsentOptionModel consentOptionModel, JsonSerializerOptions jsonSerializerOptions)
        {
            if (consentOptionModel.TitleOption.IsSet && consentOptionModel.Title == null)
                throw new ArgumentNullException(nameof(consentOptionModel.Title), "Property is required for class ConsentOptionModel.");

            if (consentOptionModel.DescriptionOption.IsSet && consentOptionModel.Description == null)
                throw new ArgumentNullException(nameof(consentOptionModel.Description), "Property is required for class ConsentOptionModel.");

            if (consentOptionModel.TitleOption.IsSet)
                writer.WriteString("Title", consentOptionModel.Title);

            if (consentOptionModel.DescriptionOption.IsSet)
                writer.WriteString("Description", consentOptionModel.Description);
        }
    }
}
