// <auto-generated>
/*
 * LoginRadius API
 *
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LoginRadius.Sdk.Internal.OpenApi.Client;

namespace LoginRadius.Sdk.Internal.OpenApi.Model
{
    /// <summary>
    /// EmailTemplateModel
    /// </summary>
    public partial class EmailTemplateModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EmailTemplateModel" /> class.
        /// </summary>
        /// <param name="templateType">The type of the Email template</param>
        /// <param name="template">The content of the Email template</param>
        /// <param name="subject">The subject of the Email template</param>
        /// <param name="templateName">The name of the Email template</param>
        /// <param name="textTemplate">The text version of the Email template</param>
        /// <param name="fromName">The name of the sender</param>
        /// <param name="fromEmail">The Email address of the sender</param>
        /// <param name="emailConfigId">Email configuration ID for sending this template.</param>
        /// <param name="isDefault">Set to true to mark this template as the default for its TemplateType. (default to false)</param>
        /// <param name="verificationTokenType">The Email Verification token type for the template.  This will be set only for &#39;registration&#39;,&#39;forgotpassword&#39;,&#39;deleteaccount&#39;,&#39;add_email&#39;,&#39;oneclicksignin&#39;, &#39;autologin&#39;,&#39;noregistrationpasswordlesslogin&#39;,&#39;forgotpin&#39;,&#39;breached_password&#39; and &#39;forget_passkey&#39; templates. </param>
        [JsonConstructor]
        public EmailTemplateModel(TemplateTypeEnum templateType, string template, string subject, Option<string?> templateName = default, Option<string?> textTemplate = default, Option<string?> fromName = default, Option<string?> fromEmail = default, Option<string?> emailConfigId = default, Option<bool?> isDefault = default, Option<VerificationTokenTypeEnum?> verificationTokenType = default)
        {
            TemplateType = templateType;
            Template = template;
            Subject = subject;
            TemplateNameOption = templateName;
            TextTemplateOption = textTemplate;
            FromNameOption = fromName;
            FromEmailOption = fromEmail;
            EmailConfigIdOption = emailConfigId;
            IsDefaultOption = isDefault;
            VerificationTokenTypeOption = verificationTokenType;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The type of the Email template
        /// </summary>
        /// <value>The type of the Email template</value>
        public enum TemplateTypeEnum
        {
            /// <summary>
            /// Enum Registration for value: registration
            /// </summary>
            Registration = 1,

            /// <summary>
            /// Enum Forgotpassword for value: forgotpassword
            /// </summary>
            Forgotpassword = 2,

            /// <summary>
            /// Enum Forgotprovider for value: forgotprovider
            /// </summary>
            Forgotprovider = 3,

            /// <summary>
            /// Enum Deleteaccount for value: deleteaccount
            /// </summary>
            Deleteaccount = 4,

            /// <summary>
            /// Enum AddEmail for value: add_email
            /// </summary>
            AddEmail = 5,

            /// <summary>
            /// Enum Welcome for value: welcome
            /// </summary>
            Welcome = 6,

            /// <summary>
            /// Enum Oneclicksignin for value: oneclicksignin
            /// </summary>
            Oneclicksignin = 7,

            /// <summary>
            /// Enum Autologin for value: autologin
            /// </summary>
            Autologin = 8,

            /// <summary>
            /// Enum Noregistrationpasswordlesslogin for value: noregistrationpasswordlesslogin
            /// </summary>
            Noregistrationpasswordlesslogin = 9,

            /// <summary>
            /// Enum Resetpassword for value: resetpassword
            /// </summary>
            Resetpassword = 10,

            /// <summary>
            /// Enum SuspiciousIpEmailToUser for value: suspicious_ip_email_to_user
            /// </summary>
            SuspiciousIpEmailToUser = 11,

            /// <summary>
            /// Enum SuspiciousCityEmailToUser for value: suspicious_city_email_to_user
            /// </summary>
            SuspiciousCityEmailToUser = 12,

            /// <summary>
            /// Enum SuspiciousCountryEmailToUser for value: suspicious_country_email_to_user
            /// </summary>
            SuspiciousCountryEmailToUser = 13,

            /// <summary>
            /// Enum SuspiciousBrowserEmailToUser for value: suspicious_browser_email_to_user
            /// </summary>
            SuspiciousBrowserEmailToUser = 14,

            /// <summary>
            /// Enum RiskIdentifiedToAdmin for value: risk_identified_to_admin
            /// </summary>
            RiskIdentifiedToAdmin = 15,

            /// <summary>
            /// Enum Forgotpin for value: forgotpin
            /// </summary>
            Forgotpin = 16,

            /// <summary>
            /// Enum Secondfactorauthentication for value: secondfactorauthentication
            /// </summary>
            Secondfactorauthentication = 17,

            /// <summary>
            /// Enum InviteUserToOrganization for value: invite_user_to_organization
            /// </summary>
            InviteUserToOrganization = 18,

            /// <summary>
            /// Enum SuspiciousDeviceEmailToUser for value: suspicious_device_email_to_user
            /// </summary>
            SuspiciousDeviceEmailToUser = 19,

            /// <summary>
            /// Enum BreachedPassword for value: breached_password
            /// </summary>
            BreachedPassword = 20,

            /// <summary>
            /// Enum AdminNotificationBreachedPassword for value: admin_notification_breached_password
            /// </summary>
            AdminNotificationBreachedPassword = 21,

            /// <summary>
            /// Enum AddPasskey for value: add_passkey
            /// </summary>
            AddPasskey = 22,

            /// <summary>
            /// Enum DeletePasskey for value: delete_passkey
            /// </summary>
            DeletePasskey = 23,

            /// <summary>
            /// Enum ForgetPasskey for value: forget_passkey
            /// </summary>
            ForgetPasskey = 24
        }

        /// <summary>
        /// Returns a <see cref="TemplateTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TemplateTypeEnum TemplateTypeEnumFromString(string value)
        {
            if (value.Equals("registration"))
                return TemplateTypeEnum.Registration;

            if (value.Equals("forgotpassword"))
                return TemplateTypeEnum.Forgotpassword;

            if (value.Equals("forgotprovider"))
                return TemplateTypeEnum.Forgotprovider;

            if (value.Equals("deleteaccount"))
                return TemplateTypeEnum.Deleteaccount;

            if (value.Equals("add_email"))
                return TemplateTypeEnum.AddEmail;

            if (value.Equals("welcome"))
                return TemplateTypeEnum.Welcome;

            if (value.Equals("oneclicksignin"))
                return TemplateTypeEnum.Oneclicksignin;

            if (value.Equals("autologin"))
                return TemplateTypeEnum.Autologin;

            if (value.Equals("noregistrationpasswordlesslogin"))
                return TemplateTypeEnum.Noregistrationpasswordlesslogin;

            if (value.Equals("resetpassword"))
                return TemplateTypeEnum.Resetpassword;

            if (value.Equals("suspicious_ip_email_to_user"))
                return TemplateTypeEnum.SuspiciousIpEmailToUser;

            if (value.Equals("suspicious_city_email_to_user"))
                return TemplateTypeEnum.SuspiciousCityEmailToUser;

            if (value.Equals("suspicious_country_email_to_user"))
                return TemplateTypeEnum.SuspiciousCountryEmailToUser;

            if (value.Equals("suspicious_browser_email_to_user"))
                return TemplateTypeEnum.SuspiciousBrowserEmailToUser;

            if (value.Equals("risk_identified_to_admin"))
                return TemplateTypeEnum.RiskIdentifiedToAdmin;

            if (value.Equals("forgotpin"))
                return TemplateTypeEnum.Forgotpin;

            if (value.Equals("secondfactorauthentication"))
                return TemplateTypeEnum.Secondfactorauthentication;

            if (value.Equals("invite_user_to_organization"))
                return TemplateTypeEnum.InviteUserToOrganization;

            if (value.Equals("suspicious_device_email_to_user"))
                return TemplateTypeEnum.SuspiciousDeviceEmailToUser;

            if (value.Equals("breached_password"))
                return TemplateTypeEnum.BreachedPassword;

            if (value.Equals("admin_notification_breached_password"))
                return TemplateTypeEnum.AdminNotificationBreachedPassword;

            if (value.Equals("add_passkey"))
                return TemplateTypeEnum.AddPasskey;

            if (value.Equals("delete_passkey"))
                return TemplateTypeEnum.DeletePasskey;

            if (value.Equals("forget_passkey"))
                return TemplateTypeEnum.ForgetPasskey;

            throw new NotImplementedException($"Could not convert value to type TemplateTypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TemplateTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TemplateTypeEnum? TemplateTypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("registration"))
                return TemplateTypeEnum.Registration;

            if (value.Equals("forgotpassword"))
                return TemplateTypeEnum.Forgotpassword;

            if (value.Equals("forgotprovider"))
                return TemplateTypeEnum.Forgotprovider;

            if (value.Equals("deleteaccount"))
                return TemplateTypeEnum.Deleteaccount;

            if (value.Equals("add_email"))
                return TemplateTypeEnum.AddEmail;

            if (value.Equals("welcome"))
                return TemplateTypeEnum.Welcome;

            if (value.Equals("oneclicksignin"))
                return TemplateTypeEnum.Oneclicksignin;

            if (value.Equals("autologin"))
                return TemplateTypeEnum.Autologin;

            if (value.Equals("noregistrationpasswordlesslogin"))
                return TemplateTypeEnum.Noregistrationpasswordlesslogin;

            if (value.Equals("resetpassword"))
                return TemplateTypeEnum.Resetpassword;

            if (value.Equals("suspicious_ip_email_to_user"))
                return TemplateTypeEnum.SuspiciousIpEmailToUser;

            if (value.Equals("suspicious_city_email_to_user"))
                return TemplateTypeEnum.SuspiciousCityEmailToUser;

            if (value.Equals("suspicious_country_email_to_user"))
                return TemplateTypeEnum.SuspiciousCountryEmailToUser;

            if (value.Equals("suspicious_browser_email_to_user"))
                return TemplateTypeEnum.SuspiciousBrowserEmailToUser;

            if (value.Equals("risk_identified_to_admin"))
                return TemplateTypeEnum.RiskIdentifiedToAdmin;

            if (value.Equals("forgotpin"))
                return TemplateTypeEnum.Forgotpin;

            if (value.Equals("secondfactorauthentication"))
                return TemplateTypeEnum.Secondfactorauthentication;

            if (value.Equals("invite_user_to_organization"))
                return TemplateTypeEnum.InviteUserToOrganization;

            if (value.Equals("suspicious_device_email_to_user"))
                return TemplateTypeEnum.SuspiciousDeviceEmailToUser;

            if (value.Equals("breached_password"))
                return TemplateTypeEnum.BreachedPassword;

            if (value.Equals("admin_notification_breached_password"))
                return TemplateTypeEnum.AdminNotificationBreachedPassword;

            if (value.Equals("add_passkey"))
                return TemplateTypeEnum.AddPasskey;

            if (value.Equals("delete_passkey"))
                return TemplateTypeEnum.DeletePasskey;

            if (value.Equals("forget_passkey"))
                return TemplateTypeEnum.ForgetPasskey;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TemplateTypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TemplateTypeEnumToJsonValue(TemplateTypeEnum value)
        {
            if (value == TemplateTypeEnum.Registration)
                return "registration";

            if (value == TemplateTypeEnum.Forgotpassword)
                return "forgotpassword";

            if (value == TemplateTypeEnum.Forgotprovider)
                return "forgotprovider";

            if (value == TemplateTypeEnum.Deleteaccount)
                return "deleteaccount";

            if (value == TemplateTypeEnum.AddEmail)
                return "add_email";

            if (value == TemplateTypeEnum.Welcome)
                return "welcome";

            if (value == TemplateTypeEnum.Oneclicksignin)
                return "oneclicksignin";

            if (value == TemplateTypeEnum.Autologin)
                return "autologin";

            if (value == TemplateTypeEnum.Noregistrationpasswordlesslogin)
                return "noregistrationpasswordlesslogin";

            if (value == TemplateTypeEnum.Resetpassword)
                return "resetpassword";

            if (value == TemplateTypeEnum.SuspiciousIpEmailToUser)
                return "suspicious_ip_email_to_user";

            if (value == TemplateTypeEnum.SuspiciousCityEmailToUser)
                return "suspicious_city_email_to_user";

            if (value == TemplateTypeEnum.SuspiciousCountryEmailToUser)
                return "suspicious_country_email_to_user";

            if (value == TemplateTypeEnum.SuspiciousBrowserEmailToUser)
                return "suspicious_browser_email_to_user";

            if (value == TemplateTypeEnum.RiskIdentifiedToAdmin)
                return "risk_identified_to_admin";

            if (value == TemplateTypeEnum.Forgotpin)
                return "forgotpin";

            if (value == TemplateTypeEnum.Secondfactorauthentication)
                return "secondfactorauthentication";

            if (value == TemplateTypeEnum.InviteUserToOrganization)
                return "invite_user_to_organization";

            if (value == TemplateTypeEnum.SuspiciousDeviceEmailToUser)
                return "suspicious_device_email_to_user";

            if (value == TemplateTypeEnum.BreachedPassword)
                return "breached_password";

            if (value == TemplateTypeEnum.AdminNotificationBreachedPassword)
                return "admin_notification_breached_password";

            if (value == TemplateTypeEnum.AddPasskey)
                return "add_passkey";

            if (value == TemplateTypeEnum.DeletePasskey)
                return "delete_passkey";

            if (value == TemplateTypeEnum.ForgetPasskey)
                return "forget_passkey";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// The type of the Email template
        /// </summary>
        /// <value>The type of the Email template</value>
        [JsonPropertyName("TemplateType")]
        public TemplateTypeEnum TemplateType { get; set; }

        /// <summary>
        /// The Email Verification token type for the template.  This will be set only for &#39;registration&#39;,&#39;forgotpassword&#39;,&#39;deleteaccount&#39;,&#39;add_email&#39;,&#39;oneclicksignin&#39;, &#39;autologin&#39;,&#39;noregistrationpasswordlesslogin&#39;,&#39;forgotpin&#39;,&#39;breached_password&#39; and &#39;forget_passkey&#39; templates. 
        /// </summary>
        /// <value>The Email Verification token type for the template.  This will be set only for &#39;registration&#39;,&#39;forgotpassword&#39;,&#39;deleteaccount&#39;,&#39;add_email&#39;,&#39;oneclicksignin&#39;, &#39;autologin&#39;,&#39;noregistrationpasswordlesslogin&#39;,&#39;forgotpin&#39;,&#39;breached_password&#39; and &#39;forget_passkey&#39; templates. </value>
        public enum VerificationTokenTypeEnum
        {
            /// <summary>
            /// Enum MagicLink for value: MagicLink
            /// </summary>
            MagicLink = 1,

            /// <summary>
            /// Enum Otp for value: Otp
            /// </summary>
            Otp = 2
        }

        /// <summary>
        /// Returns a <see cref="VerificationTokenTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static VerificationTokenTypeEnum VerificationTokenTypeEnumFromString(string value)
        {
            if (value.Equals("MagicLink"))
                return VerificationTokenTypeEnum.MagicLink;

            if (value.Equals("Otp"))
                return VerificationTokenTypeEnum.Otp;

            throw new NotImplementedException($"Could not convert value to type VerificationTokenTypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="VerificationTokenTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static VerificationTokenTypeEnum? VerificationTokenTypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("MagicLink"))
                return VerificationTokenTypeEnum.MagicLink;

            if (value.Equals("Otp"))
                return VerificationTokenTypeEnum.Otp;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="VerificationTokenTypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string VerificationTokenTypeEnumToJsonValue(VerificationTokenTypeEnum? value)
        {
            if (value == VerificationTokenTypeEnum.MagicLink)
                return "MagicLink";

            if (value == VerificationTokenTypeEnum.Otp)
                return "Otp";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of VerificationTokenType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<VerificationTokenTypeEnum?> VerificationTokenTypeOption { get; private set; }

        /// <summary>
        /// The Email Verification token type for the template.  This will be set only for &#39;registration&#39;,&#39;forgotpassword&#39;,&#39;deleteaccount&#39;,&#39;add_email&#39;,&#39;oneclicksignin&#39;, &#39;autologin&#39;,&#39;noregistrationpasswordlesslogin&#39;,&#39;forgotpin&#39;,&#39;breached_password&#39; and &#39;forget_passkey&#39; templates. 
        /// </summary>
        /// <value>The Email Verification token type for the template.  This will be set only for &#39;registration&#39;,&#39;forgotpassword&#39;,&#39;deleteaccount&#39;,&#39;add_email&#39;,&#39;oneclicksignin&#39;, &#39;autologin&#39;,&#39;noregistrationpasswordlesslogin&#39;,&#39;forgotpin&#39;,&#39;breached_password&#39; and &#39;forget_passkey&#39; templates. </value>
        [JsonPropertyName("VerificationTokenType")]
        public VerificationTokenTypeEnum? VerificationTokenType { get { return this.VerificationTokenTypeOption; } set { this.VerificationTokenTypeOption = new(value); } }

        /// <summary>
        /// The content of the Email template
        /// </summary>
        /// <value>The content of the Email template</value>
        [JsonPropertyName("Template")]
        public string Template { get; set; }

        /// <summary>
        /// The subject of the Email template
        /// </summary>
        /// <value>The subject of the Email template</value>
        [JsonPropertyName("Subject")]
        public string Subject { get; set; }

        /// <summary>
        /// Used to track the state of TemplateName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TemplateNameOption { get; private set; }

        /// <summary>
        /// The name of the Email template
        /// </summary>
        /// <value>The name of the Email template</value>
        [JsonPropertyName("TemplateName")]
        public string? TemplateName { get { return this.TemplateNameOption; } set { this.TemplateNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of TextTemplate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TextTemplateOption { get; private set; }

        /// <summary>
        /// The text version of the Email template
        /// </summary>
        /// <value>The text version of the Email template</value>
        [JsonPropertyName("TextTemplate")]
        public string? TextTemplate { get { return this.TextTemplateOption; } set { this.TextTemplateOption = new(value); } }

        /// <summary>
        /// Used to track the state of FromName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FromNameOption { get; private set; }

        /// <summary>
        /// The name of the sender
        /// </summary>
        /// <value>The name of the sender</value>
        [JsonPropertyName("FromName")]
        public string? FromName { get { return this.FromNameOption; } set { this.FromNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of FromEmail
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FromEmailOption { get; private set; }

        /// <summary>
        /// The Email address of the sender
        /// </summary>
        /// <value>The Email address of the sender</value>
        [JsonPropertyName("FromEmail")]
        public string? FromEmail { get { return this.FromEmailOption; } set { this.FromEmailOption = new(value); } }

        /// <summary>
        /// Used to track the state of EmailConfigId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EmailConfigIdOption { get; private set; }

        /// <summary>
        /// Email configuration ID for sending this template.
        /// </summary>
        /// <value>Email configuration ID for sending this template.</value>
        [JsonPropertyName("EmailConfigId")]
        public string? EmailConfigId { get { return this.EmailConfigIdOption; } set { this.EmailConfigIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsDefault
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsDefaultOption { get; private set; }

        /// <summary>
        /// Set to true to mark this template as the default for its TemplateType.
        /// </summary>
        /// <value>Set to true to mark this template as the default for its TemplateType.</value>
        [JsonPropertyName("IsDefault")]
        public bool? IsDefault { get { return this.IsDefaultOption; } set { this.IsDefaultOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EmailTemplateModel {\n");
            sb.Append("  TemplateType: ").Append(TemplateType).Append("\n");
            sb.Append("  Template: ").Append(Template).Append("\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  TemplateName: ").Append(TemplateName).Append("\n");
            sb.Append("  TextTemplate: ").Append(TextTemplate).Append("\n");
            sb.Append("  FromName: ").Append(FromName).Append("\n");
            sb.Append("  FromEmail: ").Append(FromEmail).Append("\n");
            sb.Append("  EmailConfigId: ").Append(EmailConfigId).Append("\n");
            sb.Append("  IsDefault: ").Append(IsDefault).Append("\n");
            sb.Append("  VerificationTokenType: ").Append(VerificationTokenType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EmailTemplateModel" />
    /// </summary>
    public class EmailTemplateModelJsonConverter : JsonConverter<EmailTemplateModel>
    {
        /// <summary>
        /// Deserializes json to <see cref="EmailTemplateModel" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EmailTemplateModel Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<EmailTemplateModel.TemplateTypeEnum?> templateType = default;
            Option<string?> template = default;
            Option<string?> subject = default;
            Option<string?> templateName = default;
            Option<string?> textTemplate = default;
            Option<string?> fromName = default;
            Option<string?> fromEmail = default;
            Option<string?> emailConfigId = default;
            Option<bool?> isDefault = default;
            Option<EmailTemplateModel.VerificationTokenTypeEnum?> verificationTokenType = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "TemplateType":
                            string? templateTypeRawValue = utf8JsonReader.GetString();
                            if (templateTypeRawValue != null)
                                templateType = new Option<EmailTemplateModel.TemplateTypeEnum?>(EmailTemplateModel.TemplateTypeEnumFromStringOrDefault(templateTypeRawValue));
                            break;
                        case "Template":
                            template = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "Subject":
                            subject = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "TemplateName":
                            templateName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "TextTemplate":
                            textTemplate = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "FromName":
                            fromName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "FromEmail":
                            fromEmail = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "EmailConfigId":
                            emailConfigId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "IsDefault":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                isDefault = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "VerificationTokenType":
                            string? verificationTokenTypeRawValue = utf8JsonReader.GetString();
                            if (verificationTokenTypeRawValue != null)
                                verificationTokenType = new Option<EmailTemplateModel.VerificationTokenTypeEnum?>(EmailTemplateModel.VerificationTokenTypeEnumFromStringOrDefault(verificationTokenTypeRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!templateType.IsSet)
                throw new ArgumentException("Property is required for class EmailTemplateModel.", nameof(templateType));

            if (!template.IsSet)
                throw new ArgumentException("Property is required for class EmailTemplateModel.", nameof(template));

            if (!subject.IsSet)
                throw new ArgumentException("Property is required for class EmailTemplateModel.", nameof(subject));

            if (templateType.IsSet && templateType.Value == null)
                throw new ArgumentNullException(nameof(templateType), "Property is not nullable for class EmailTemplateModel.");

            if (template.IsSet && template.Value == null)
                throw new ArgumentNullException(nameof(template), "Property is not nullable for class EmailTemplateModel.");

            if (subject.IsSet && subject.Value == null)
                throw new ArgumentNullException(nameof(subject), "Property is not nullable for class EmailTemplateModel.");

            if (templateName.IsSet && templateName.Value == null)
                throw new ArgumentNullException(nameof(templateName), "Property is not nullable for class EmailTemplateModel.");

            if (textTemplate.IsSet && textTemplate.Value == null)
                throw new ArgumentNullException(nameof(textTemplate), "Property is not nullable for class EmailTemplateModel.");

            if (fromName.IsSet && fromName.Value == null)
                throw new ArgumentNullException(nameof(fromName), "Property is not nullable for class EmailTemplateModel.");

            if (fromEmail.IsSet && fromEmail.Value == null)
                throw new ArgumentNullException(nameof(fromEmail), "Property is not nullable for class EmailTemplateModel.");

            if (emailConfigId.IsSet && emailConfigId.Value == null)
                throw new ArgumentNullException(nameof(emailConfigId), "Property is not nullable for class EmailTemplateModel.");

            if (isDefault.IsSet && isDefault.Value == null)
                throw new ArgumentNullException(nameof(isDefault), "Property is not nullable for class EmailTemplateModel.");

            if (verificationTokenType.IsSet && verificationTokenType.Value == null)
                throw new ArgumentNullException(nameof(verificationTokenType), "Property is not nullable for class EmailTemplateModel.");

            return new EmailTemplateModel(templateType.Value!.Value!, template.Value!, subject.Value!, templateName, textTemplate, fromName, fromEmail, emailConfigId, isDefault, verificationTokenType);
        }

        /// <summary>
        /// Serializes a <see cref="EmailTemplateModel" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="emailTemplateModel"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EmailTemplateModel emailTemplateModel, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, emailTemplateModel, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EmailTemplateModel" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="emailTemplateModel"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EmailTemplateModel emailTemplateModel, JsonSerializerOptions jsonSerializerOptions)
        {
            if (emailTemplateModel.Template == null)
                throw new ArgumentNullException(nameof(emailTemplateModel.Template), "Property is required for class EmailTemplateModel.");

            if (emailTemplateModel.Subject == null)
                throw new ArgumentNullException(nameof(emailTemplateModel.Subject), "Property is required for class EmailTemplateModel.");

            if (emailTemplateModel.TemplateNameOption.IsSet && emailTemplateModel.TemplateName == null)
                throw new ArgumentNullException(nameof(emailTemplateModel.TemplateName), "Property is required for class EmailTemplateModel.");

            if (emailTemplateModel.TextTemplateOption.IsSet && emailTemplateModel.TextTemplate == null)
                throw new ArgumentNullException(nameof(emailTemplateModel.TextTemplate), "Property is required for class EmailTemplateModel.");

            if (emailTemplateModel.FromNameOption.IsSet && emailTemplateModel.FromName == null)
                throw new ArgumentNullException(nameof(emailTemplateModel.FromName), "Property is required for class EmailTemplateModel.");

            if (emailTemplateModel.FromEmailOption.IsSet && emailTemplateModel.FromEmail == null)
                throw new ArgumentNullException(nameof(emailTemplateModel.FromEmail), "Property is required for class EmailTemplateModel.");

            if (emailTemplateModel.EmailConfigIdOption.IsSet && emailTemplateModel.EmailConfigId == null)
                throw new ArgumentNullException(nameof(emailTemplateModel.EmailConfigId), "Property is required for class EmailTemplateModel.");

            var templateTypeRawValue = EmailTemplateModel.TemplateTypeEnumToJsonValue(emailTemplateModel.TemplateType);
            writer.WriteString("TemplateType", templateTypeRawValue);
            writer.WriteString("Template", emailTemplateModel.Template);

            writer.WriteString("Subject", emailTemplateModel.Subject);

            if (emailTemplateModel.TemplateNameOption.IsSet)
                writer.WriteString("TemplateName", emailTemplateModel.TemplateName);

            if (emailTemplateModel.TextTemplateOption.IsSet)
                writer.WriteString("TextTemplate", emailTemplateModel.TextTemplate);

            if (emailTemplateModel.FromNameOption.IsSet)
                writer.WriteString("FromName", emailTemplateModel.FromName);

            if (emailTemplateModel.FromEmailOption.IsSet)
                writer.WriteString("FromEmail", emailTemplateModel.FromEmail);

            if (emailTemplateModel.EmailConfigIdOption.IsSet)
                writer.WriteString("EmailConfigId", emailTemplateModel.EmailConfigId);

            if (emailTemplateModel.IsDefaultOption.IsSet)
                writer.WriteBoolean("IsDefault", emailTemplateModel.IsDefaultOption.Value!.Value);

            var verificationTokenTypeRawValue = EmailTemplateModel.VerificationTokenTypeEnumToJsonValue(emailTemplateModel.VerificationTokenTypeOption.Value!.Value);
            writer.WriteString("VerificationTokenType", verificationTokenTypeRawValue);
        }
    }
}
