// <auto-generated>
/*
 * LoginRadius API
 *
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LoginRadius.Sdk.Internal.OpenApi.Client;

namespace LoginRadius.Sdk.Internal.OpenApi.Model
{
    /// <summary>
    /// IdentityProvider
    /// </summary>
    public partial class IdentityProvider : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IdentityProvider" /> class.
        /// </summary>
        /// <param name="binding">binding</param>
        /// <param name="location">location</param>
        /// <param name="logOut">logOut</param>
        [JsonConstructor]
        public IdentityProvider(Option<string?> binding = default, Option<string?> location = default, Option<string?> logOut = default)
        {
            BindingOption = binding;
            LocationOption = location;
            LogOutOption = logOut;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Binding
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> BindingOption { get; private set; }

        /// <summary>
        /// Gets or Sets Binding
        /// </summary>
        /* <example>binding</example> */
        [JsonPropertyName("Binding")]
        public string? Binding { get { return this.BindingOption; } set { this.BindingOption = new(value); } }

        /// <summary>
        /// Used to track the state of Location
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LocationOption { get; private set; }

        /// <summary>
        /// Gets or Sets Location
        /// </summary>
        /* <example>location</example> */
        [JsonPropertyName("Location")]
        public string? Location { get { return this.LocationOption; } set { this.LocationOption = new(value); } }

        /// <summary>
        /// Used to track the state of LogOut
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LogOutOption { get; private set; }

        /// <summary>
        /// Gets or Sets LogOut
        /// </summary>
        /* <example>logout</example> */
        [JsonPropertyName("LogOut")]
        public string? LogOut { get { return this.LogOutOption; } set { this.LogOutOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IdentityProvider {\n");
            sb.Append("  Binding: ").Append(Binding).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("  LogOut: ").Append(LogOut).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="IdentityProvider" />
    /// </summary>
    public class IdentityProviderJsonConverter : JsonConverter<IdentityProvider>
    {
        /// <summary>
        /// Deserializes json to <see cref="IdentityProvider" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override IdentityProvider Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> binding = default;
            Option<string?> location = default;
            Option<string?> logOut = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "Binding":
                            binding = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "Location":
                            location = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "LogOut":
                            logOut = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            return new IdentityProvider(binding, location, logOut);
        }

        /// <summary>
        /// Serializes a <see cref="IdentityProvider" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="identityProvider"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, IdentityProvider identityProvider, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, identityProvider, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="IdentityProvider" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="identityProvider"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, IdentityProvider identityProvider, JsonSerializerOptions jsonSerializerOptions)
        {
            if (identityProvider.BindingOption.IsSet)
                if (identityProvider.BindingOption.Value != null)
                    writer.WriteString("Binding", identityProvider.Binding);
                else
                    writer.WriteNull("Binding");

            if (identityProvider.LocationOption.IsSet)
                if (identityProvider.LocationOption.Value != null)
                    writer.WriteString("Location", identityProvider.Location);
                else
                    writer.WriteNull("Location");

            if (identityProvider.LogOutOption.IsSet)
                if (identityProvider.LogOutOption.Value != null)
                    writer.WriteString("LogOut", identityProvider.LogOut);
                else
                    writer.WriteNull("LogOut");
        }
    }
}
