// <auto-generated>
/*
 * LoginRadius API
 *
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LoginRadius.Sdk.Internal.OpenApi.Client;

namespace LoginRadius.Sdk.Internal.OpenApi.Model
{
    /// <summary>
    /// ManageRegisterModelJobBookmarksInner
    /// </summary>
    public partial class ManageRegisterModelJobBookmarksInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ManageRegisterModelJobBookmarksInner" /> class.
        /// </summary>
        /// <param name="isApplied">Indicates if the job has been applied for.</param>
        /// <param name="isSaved">Indicates if the job has been saved.</param>
        /// <param name="applyTimestamp">The timestamp when the job was applied for.</param>
        /// <param name="savedTimestamp">The timestamp when the job was saved.</param>
        /// <param name="job">job</param>
        [JsonConstructor]
        public ManageRegisterModelJobBookmarksInner(Option<bool?> isApplied = default, Option<bool?> isSaved = default, Option<DateTime?> applyTimestamp = default, Option<DateTime?> savedTimestamp = default, Option<ManageRegisterModelJobBookmarksInnerJob?> job = default)
        {
            IsAppliedOption = isApplied;
            IsSavedOption = isSaved;
            ApplyTimestampOption = applyTimestamp;
            SavedTimestampOption = savedTimestamp;
            JobOption = job;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of IsApplied
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsAppliedOption { get; private set; }

        /// <summary>
        /// Indicates if the job has been applied for.
        /// </summary>
        /// <value>Indicates if the job has been applied for.</value>
        /* <example>true</example> */
        [JsonPropertyName("IsApplied")]
        public bool? IsApplied { get { return this.IsAppliedOption; } set { this.IsAppliedOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsSaved
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsSavedOption { get; private set; }

        /// <summary>
        /// Indicates if the job has been saved.
        /// </summary>
        /// <value>Indicates if the job has been saved.</value>
        /* <example>true</example> */
        [JsonPropertyName("IsSaved")]
        public bool? IsSaved { get { return this.IsSavedOption; } set { this.IsSavedOption = new(value); } }

        /// <summary>
        /// Used to track the state of ApplyTimestamp
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> ApplyTimestampOption { get; private set; }

        /// <summary>
        /// The timestamp when the job was applied for.
        /// </summary>
        /// <value>The timestamp when the job was applied for.</value>
        /* <example>2023-05-15T10:00Z</example> */
        [JsonPropertyName("ApplyTimestamp")]
        public DateTime? ApplyTimestamp { get { return this.ApplyTimestampOption; } set { this.ApplyTimestampOption = new(value); } }

        /// <summary>
        /// Used to track the state of SavedTimestamp
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> SavedTimestampOption { get; private set; }

        /// <summary>
        /// The timestamp when the job was saved.
        /// </summary>
        /// <value>The timestamp when the job was saved.</value>
        /* <example>2023-05-10T10:00Z</example> */
        [JsonPropertyName("SavedTimestamp")]
        public DateTime? SavedTimestamp { get { return this.SavedTimestampOption; } set { this.SavedTimestampOption = new(value); } }

        /// <summary>
        /// Used to track the state of Job
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ManageRegisterModelJobBookmarksInnerJob?> JobOption { get; private set; }

        /// <summary>
        /// Gets or Sets Job
        /// </summary>
        [JsonPropertyName("Job")]
        public ManageRegisterModelJobBookmarksInnerJob? Job { get { return this.JobOption; } set { this.JobOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ManageRegisterModelJobBookmarksInner {\n");
            sb.Append("  IsApplied: ").Append(IsApplied).Append("\n");
            sb.Append("  IsSaved: ").Append(IsSaved).Append("\n");
            sb.Append("  ApplyTimestamp: ").Append(ApplyTimestamp).Append("\n");
            sb.Append("  SavedTimestamp: ").Append(SavedTimestamp).Append("\n");
            sb.Append("  Job: ").Append(Job).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ManageRegisterModelJobBookmarksInner" />
    /// </summary>
    public class ManageRegisterModelJobBookmarksInnerJsonConverter : JsonConverter<ManageRegisterModelJobBookmarksInner>
    {
        /// <summary>
        /// The format to use to serialize ApplyTimestamp
        /// </summary>
        public static string ApplyTimestampFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize SavedTimestamp
        /// </summary>
        public static string SavedTimestampFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="ManageRegisterModelJobBookmarksInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ManageRegisterModelJobBookmarksInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> isApplied = default;
            Option<bool?> isSaved = default;
            Option<DateTime?> applyTimestamp = default;
            Option<DateTime?> savedTimestamp = default;
            Option<ManageRegisterModelJobBookmarksInnerJob?> job = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "IsApplied":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                isApplied = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "IsSaved":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                isSaved = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "ApplyTimestamp":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                applyTimestamp = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "SavedTimestamp":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                savedTimestamp = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "Job":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                job = new Option<ManageRegisterModelJobBookmarksInnerJob?>(JsonSerializer.Deserialize<ManageRegisterModelJobBookmarksInnerJob>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (isApplied.IsSet && isApplied.Value == null)
                throw new ArgumentNullException(nameof(isApplied), "Property is not nullable for class ManageRegisterModelJobBookmarksInner.");

            if (isSaved.IsSet && isSaved.Value == null)
                throw new ArgumentNullException(nameof(isSaved), "Property is not nullable for class ManageRegisterModelJobBookmarksInner.");

            if (applyTimestamp.IsSet && applyTimestamp.Value == null)
                throw new ArgumentNullException(nameof(applyTimestamp), "Property is not nullable for class ManageRegisterModelJobBookmarksInner.");

            if (savedTimestamp.IsSet && savedTimestamp.Value == null)
                throw new ArgumentNullException(nameof(savedTimestamp), "Property is not nullable for class ManageRegisterModelJobBookmarksInner.");

            if (job.IsSet && job.Value == null)
                throw new ArgumentNullException(nameof(job), "Property is not nullable for class ManageRegisterModelJobBookmarksInner.");

            return new ManageRegisterModelJobBookmarksInner(isApplied, isSaved, applyTimestamp, savedTimestamp, job);
        }

        /// <summary>
        /// Serializes a <see cref="ManageRegisterModelJobBookmarksInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="manageRegisterModelJobBookmarksInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ManageRegisterModelJobBookmarksInner manageRegisterModelJobBookmarksInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, manageRegisterModelJobBookmarksInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ManageRegisterModelJobBookmarksInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="manageRegisterModelJobBookmarksInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ManageRegisterModelJobBookmarksInner manageRegisterModelJobBookmarksInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (manageRegisterModelJobBookmarksInner.JobOption.IsSet && manageRegisterModelJobBookmarksInner.Job == null)
                throw new ArgumentNullException(nameof(manageRegisterModelJobBookmarksInner.Job), "Property is required for class ManageRegisterModelJobBookmarksInner.");

            if (manageRegisterModelJobBookmarksInner.IsAppliedOption.IsSet)
                writer.WriteBoolean("IsApplied", manageRegisterModelJobBookmarksInner.IsAppliedOption.Value!.Value);

            if (manageRegisterModelJobBookmarksInner.IsSavedOption.IsSet)
                writer.WriteBoolean("IsSaved", manageRegisterModelJobBookmarksInner.IsSavedOption.Value!.Value);

            if (manageRegisterModelJobBookmarksInner.ApplyTimestampOption.IsSet)
                writer.WriteString("ApplyTimestamp", manageRegisterModelJobBookmarksInner.ApplyTimestampOption.Value!.Value.ToString(ApplyTimestampFormat));

            if (manageRegisterModelJobBookmarksInner.SavedTimestampOption.IsSet)
                writer.WriteString("SavedTimestamp", manageRegisterModelJobBookmarksInner.SavedTimestampOption.Value!.Value.ToString(SavedTimestampFormat));

            if (manageRegisterModelJobBookmarksInner.JobOption.IsSet)
            {
                writer.WritePropertyName("Job");
                JsonSerializer.Serialize(writer, manageRegisterModelJobBookmarksInner.Job, jsonSerializerOptions);
            }
        }
    }
}
