// <auto-generated>
/*
 * LoginRadius API
 *
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LoginRadius.Sdk.Internal.OpenApi.Client;

namespace LoginRadius.Sdk.Internal.OpenApi.Model
{
    /// <summary>
    /// Details of the job.
    /// </summary>
    public partial class ManageRegisterModelJobBookmarksInnerJob : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ManageRegisterModelJobBookmarksInnerJob" /> class.
        /// </summary>
        /// <param name="id">The ID of the job.</param>
        /// <param name="title">The title of the job.</param>
        /// <param name="company">The company offering the job.</param>
        [JsonConstructor]
        public ManageRegisterModelJobBookmarksInnerJob(Option<string?> id = default, Option<string?> title = default, Option<string?> company = default)
        {
            IdOption = id;
            TitleOption = title;
            CompanyOption = company;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IdOption { get; private set; }

        /// <summary>
        /// The ID of the job.
        /// </summary>
        /// <value>The ID of the job.</value>
        /* <example>job_123</example> */
        [JsonPropertyName("Id")]
        public string? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Title
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TitleOption { get; private set; }

        /// <summary>
        /// The title of the job.
        /// </summary>
        /// <value>The title of the job.</value>
        /* <example>Software Engineer</example> */
        [JsonPropertyName("Title")]
        public string? Title { get { return this.TitleOption; } set { this.TitleOption = new(value); } }

        /// <summary>
        /// Used to track the state of Company
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CompanyOption { get; private set; }

        /// <summary>
        /// The company offering the job.
        /// </summary>
        /// <value>The company offering the job.</value>
        /* <example>Tech Corp</example> */
        [JsonPropertyName("Company")]
        public string? Company { get { return this.CompanyOption; } set { this.CompanyOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ManageRegisterModelJobBookmarksInnerJob {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Company: ").Append(Company).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ManageRegisterModelJobBookmarksInnerJob" />
    /// </summary>
    public class ManageRegisterModelJobBookmarksInnerJobJsonConverter : JsonConverter<ManageRegisterModelJobBookmarksInnerJob>
    {
        /// <summary>
        /// Deserializes json to <see cref="ManageRegisterModelJobBookmarksInnerJob" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ManageRegisterModelJobBookmarksInnerJob Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<string?> title = default;
            Option<string?> company = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "Id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "Title":
                            title = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "Company":
                            company = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class ManageRegisterModelJobBookmarksInnerJob.");

            if (title.IsSet && title.Value == null)
                throw new ArgumentNullException(nameof(title), "Property is not nullable for class ManageRegisterModelJobBookmarksInnerJob.");

            if (company.IsSet && company.Value == null)
                throw new ArgumentNullException(nameof(company), "Property is not nullable for class ManageRegisterModelJobBookmarksInnerJob.");

            return new ManageRegisterModelJobBookmarksInnerJob(id, title, company);
        }

        /// <summary>
        /// Serializes a <see cref="ManageRegisterModelJobBookmarksInnerJob" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="manageRegisterModelJobBookmarksInnerJob"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ManageRegisterModelJobBookmarksInnerJob manageRegisterModelJobBookmarksInnerJob, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, manageRegisterModelJobBookmarksInnerJob, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ManageRegisterModelJobBookmarksInnerJob" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="manageRegisterModelJobBookmarksInnerJob"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ManageRegisterModelJobBookmarksInnerJob manageRegisterModelJobBookmarksInnerJob, JsonSerializerOptions jsonSerializerOptions)
        {
            if (manageRegisterModelJobBookmarksInnerJob.IdOption.IsSet && manageRegisterModelJobBookmarksInnerJob.Id == null)
                throw new ArgumentNullException(nameof(manageRegisterModelJobBookmarksInnerJob.Id), "Property is required for class ManageRegisterModelJobBookmarksInnerJob.");

            if (manageRegisterModelJobBookmarksInnerJob.TitleOption.IsSet && manageRegisterModelJobBookmarksInnerJob.Title == null)
                throw new ArgumentNullException(nameof(manageRegisterModelJobBookmarksInnerJob.Title), "Property is required for class ManageRegisterModelJobBookmarksInnerJob.");

            if (manageRegisterModelJobBookmarksInnerJob.CompanyOption.IsSet && manageRegisterModelJobBookmarksInnerJob.Company == null)
                throw new ArgumentNullException(nameof(manageRegisterModelJobBookmarksInnerJob.Company), "Property is required for class ManageRegisterModelJobBookmarksInnerJob.");

            if (manageRegisterModelJobBookmarksInnerJob.IdOption.IsSet)
                writer.WriteString("Id", manageRegisterModelJobBookmarksInnerJob.Id);

            if (manageRegisterModelJobBookmarksInnerJob.TitleOption.IsSet)
                writer.WriteString("Title", manageRegisterModelJobBookmarksInnerJob.Title);

            if (manageRegisterModelJobBookmarksInnerJob.CompanyOption.IsSet)
                writer.WriteString("Company", manageRegisterModelJobBookmarksInnerJob.Company);
        }
    }
}
