// <auto-generated>
/*
 * LoginRadius API
 *
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LoginRadius.Sdk.Internal.OpenApi.Client;

namespace LoginRadius.Sdk.Internal.OpenApi.Model
{
    /// <summary>
    /// OAuth Revoke Refresh Token Request
    /// </summary>
    public partial class OAuthRevokeRefreshToken : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OAuthRevokeRefreshToken" /> class.
        /// </summary>
        /// <param name="clientId">clientId</param>
        /// <param name="clientSecret">clientSecret</param>
        /// <param name="token">token</param>
        [JsonConstructor]
        public OAuthRevokeRefreshToken(string clientId, string clientSecret, string token)
        {
            ClientId = clientId;
            ClientSecret = clientSecret;
            Token = token;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets ClientId
        /// </summary>
        /* <example>68106262-3938-4435-87ed-3e410b360209</example> */
        [JsonPropertyName("client_id")]
        public string ClientId { get; set; }

        /// <summary>
        /// Gets or Sets ClientSecret
        /// </summary>
        /* <example>AQvsBHrjOYFNJdvndATLBPoavRZUp1fj4656</example> */
        [JsonPropertyName("client_secret")]
        public string ClientSecret { get; set; }

        /// <summary>
        /// Gets or Sets Token
        /// </summary>
        /* <example>3976a9391e31d3c1cf854c83f9f65078:90f...</example> */
        [JsonPropertyName("token")]
        public string Token { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OAuthRevokeRefreshToken {\n");
            sb.Append("  ClientId: ").Append(ClientId).Append("\n");
            sb.Append("  ClientSecret: ").Append(ClientSecret).Append("\n");
            sb.Append("  Token: ").Append(Token).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OAuthRevokeRefreshToken" />
    /// </summary>
    public class OAuthRevokeRefreshTokenJsonConverter : JsonConverter<OAuthRevokeRefreshToken>
    {
        /// <summary>
        /// Deserializes json to <see cref="OAuthRevokeRefreshToken" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OAuthRevokeRefreshToken Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> clientId = default;
            Option<string?> clientSecret = default;
            Option<string?> token = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "client_id":
                            clientId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "client_secret":
                            clientSecret = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "token":
                            token = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!clientId.IsSet)
                throw new ArgumentException("Property is required for class OAuthRevokeRefreshToken.", nameof(clientId));

            if (!clientSecret.IsSet)
                throw new ArgumentException("Property is required for class OAuthRevokeRefreshToken.", nameof(clientSecret));

            if (!token.IsSet)
                throw new ArgumentException("Property is required for class OAuthRevokeRefreshToken.", nameof(token));

            if (clientId.IsSet && clientId.Value == null)
                throw new ArgumentNullException(nameof(clientId), "Property is not nullable for class OAuthRevokeRefreshToken.");

            if (clientSecret.IsSet && clientSecret.Value == null)
                throw new ArgumentNullException(nameof(clientSecret), "Property is not nullable for class OAuthRevokeRefreshToken.");

            if (token.IsSet && token.Value == null)
                throw new ArgumentNullException(nameof(token), "Property is not nullable for class OAuthRevokeRefreshToken.");

            return new OAuthRevokeRefreshToken(clientId.Value!, clientSecret.Value!, token.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="OAuthRevokeRefreshToken" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="oAuthRevokeRefreshToken"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OAuthRevokeRefreshToken oAuthRevokeRefreshToken, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, oAuthRevokeRefreshToken, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OAuthRevokeRefreshToken" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="oAuthRevokeRefreshToken"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, OAuthRevokeRefreshToken oAuthRevokeRefreshToken, JsonSerializerOptions jsonSerializerOptions)
        {
            if (oAuthRevokeRefreshToken.ClientId == null)
                throw new ArgumentNullException(nameof(oAuthRevokeRefreshToken.ClientId), "Property is required for class OAuthRevokeRefreshToken.");

            if (oAuthRevokeRefreshToken.ClientSecret == null)
                throw new ArgumentNullException(nameof(oAuthRevokeRefreshToken.ClientSecret), "Property is required for class OAuthRevokeRefreshToken.");

            if (oAuthRevokeRefreshToken.Token == null)
                throw new ArgumentNullException(nameof(oAuthRevokeRefreshToken.Token), "Property is required for class OAuthRevokeRefreshToken.");

            writer.WriteString("client_id", oAuthRevokeRefreshToken.ClientId);

            writer.WriteString("client_secret", oAuthRevokeRefreshToken.ClientSecret);

            writer.WriteString("token", oAuthRevokeRefreshToken.Token);
        }
    }
}
