// <auto-generated>
/*
 * LoginRadius API
 *
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LoginRadius.Sdk.Internal.OpenApi.Client;

namespace LoginRadius.Sdk.Internal.OpenApi.Model
{
    /// <summary>
    /// OAuthClientRequestJwtTokenConfig
    /// </summary>
    public partial class OAuthClientRequestJwtTokenConfig : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OAuthClientRequestJwtTokenConfig" /> class.
        /// </summary>
        /// <param name="idTokenTTL">idTokenTTL</param>
        /// <param name="tokenTTL">tokenTTL</param>
        [JsonConstructor]
        public OAuthClientRequestJwtTokenConfig(Option<int?> idTokenTTL = default, Option<int?> tokenTTL = default)
        {
            IdTokenTTLOption = idTokenTTL;
            TokenTTLOption = tokenTTL;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of IdTokenTTL
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> IdTokenTTLOption { get; private set; }

        /// <summary>
        /// Gets or Sets IdTokenTTL
        /// </summary>
        /* <example>3600</example> */
        [JsonPropertyName("IdTokenTTL")]
        public int? IdTokenTTL { get { return this.IdTokenTTLOption; } set { this.IdTokenTTLOption = new(value); } }

        /// <summary>
        /// Used to track the state of TokenTTL
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TokenTTLOption { get; private set; }

        /// <summary>
        /// Gets or Sets TokenTTL
        /// </summary>
        /* <example>3600</example> */
        [JsonPropertyName("TokenTTL")]
        public int? TokenTTL { get { return this.TokenTTLOption; } set { this.TokenTTLOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OAuthClientRequestJwtTokenConfig {\n");
            sb.Append("  IdTokenTTL: ").Append(IdTokenTTL).Append("\n");
            sb.Append("  TokenTTL: ").Append(TokenTTL).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OAuthClientRequestJwtTokenConfig" />
    /// </summary>
    public class OAuthClientRequestJwtTokenConfigJsonConverter : JsonConverter<OAuthClientRequestJwtTokenConfig>
    {
        /// <summary>
        /// Deserializes json to <see cref="OAuthClientRequestJwtTokenConfig" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OAuthClientRequestJwtTokenConfig Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> idTokenTTL = default;
            Option<int?> tokenTTL = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "IdTokenTTL":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                idTokenTTL = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "TokenTTL":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                tokenTTL = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (idTokenTTL.IsSet && idTokenTTL.Value == null)
                throw new ArgumentNullException(nameof(idTokenTTL), "Property is not nullable for class OAuthClientRequestJwtTokenConfig.");

            if (tokenTTL.IsSet && tokenTTL.Value == null)
                throw new ArgumentNullException(nameof(tokenTTL), "Property is not nullable for class OAuthClientRequestJwtTokenConfig.");

            return new OAuthClientRequestJwtTokenConfig(idTokenTTL, tokenTTL);
        }

        /// <summary>
        /// Serializes a <see cref="OAuthClientRequestJwtTokenConfig" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="oAuthClientRequestJwtTokenConfig"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OAuthClientRequestJwtTokenConfig oAuthClientRequestJwtTokenConfig, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, oAuthClientRequestJwtTokenConfig, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OAuthClientRequestJwtTokenConfig" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="oAuthClientRequestJwtTokenConfig"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, OAuthClientRequestJwtTokenConfig oAuthClientRequestJwtTokenConfig, JsonSerializerOptions jsonSerializerOptions)
        {
            if (oAuthClientRequestJwtTokenConfig.IdTokenTTLOption.IsSet)
                writer.WriteNumber("IdTokenTTL", oAuthClientRequestJwtTokenConfig.IdTokenTTLOption.Value!.Value);

            if (oAuthClientRequestJwtTokenConfig.TokenTTLOption.IsSet)
                writer.WriteNumber("TokenTTL", oAuthClientRequestJwtTokenConfig.TokenTTLOption.Value!.Value);
        }
    }
}
