// <auto-generated>
/*
 * LoginRadius API
 *
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LoginRadius.Sdk.Internal.OpenApi.Client;

namespace LoginRadius.Sdk.Internal.OpenApi.Model
{
    /// <summary>
    /// OidcConnectionBase
    /// </summary>
    public partial class OidcConnectionBase : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OidcConnectionBase" /> class.
        /// </summary>
        /// <param name="authorizationUrl">The URL to the OpenID Connect provider&#39;s authorization endpoint. This is where users are redirected to authenticate and authorize access.</param>
        /// <param name="clientId">The client identifier issued to the application by the OpenID Connect provider. This is used to identify the application during the authentication process.</param>
        /// <param name="clientSecret">The client secret issued to the application by the OpenID Connect provider. This is used to authenticate the application when requesting tokens.</param>
        /// <param name="issuer">The issuer identifier for the OpenID Connect provider. This is typically the base URL of the provider and is used to validate tokens.</param>
        /// <param name="scopes">The scopes requested by the application during the authentication process. Scopes define the access level and Permissions granted to the application.</param>
        /// <param name="tokenAuthMethod">The method used to authenticate the application when requesting tokens. Common methods include &#x60;client_secret_post&#x60; and &#x60;client_secret_basic&#x60;.</param>
        /// <param name="tokenUrl">The URL to the OpenID Connect provider&#39;s token endpoint. This is where the application exchanges the authorization code for tokens.</param>
        /// <param name="userInfoUrl">The URL to the OpenID Connect provider&#39;s UserInfo endpoint.</param>
        /// <param name="userInfoExtractByIdToken">Indicates if user info should be extracted by ID token.</param>
        /// <param name="jWKSEndpoint">The JWKS endpoint for verifying the ID token.</param>
        [JsonConstructor]
        public OidcConnectionBase(Option<string?> authorizationUrl = default, Option<string?> clientId = default, Option<string?> clientSecret = default, Option<string?> issuer = default, Option<List<string>?> scopes = default, Option<string?> tokenAuthMethod = default, Option<string?> tokenUrl = default, Option<string?> userInfoUrl = default, Option<bool?> userInfoExtractByIdToken = default, Option<string?> jWKSEndpoint = default)
        {
            AuthorizationUrlOption = authorizationUrl;
            ClientIdOption = clientId;
            ClientSecretOption = clientSecret;
            IssuerOption = issuer;
            ScopesOption = scopes;
            TokenAuthMethodOption = tokenAuthMethod;
            TokenUrlOption = tokenUrl;
            UserInfoUrlOption = userInfoUrl;
            UserInfoExtractByIdTokenOption = userInfoExtractByIdToken;
            JWKSEndpointOption = jWKSEndpoint;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of AuthorizationUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AuthorizationUrlOption { get; private set; }

        /// <summary>
        /// The URL to the OpenID Connect provider&#39;s authorization endpoint. This is where users are redirected to authenticate and authorize access.
        /// </summary>
        /// <value>The URL to the OpenID Connect provider&#39;s authorization endpoint. This is where users are redirected to authenticate and authorize access.</value>
        /* <example>https://exampleIdp.com/oidc/authorize</example> */
        [JsonPropertyName("AuthorizationUrl")]
        public string? AuthorizationUrl { get { return this.AuthorizationUrlOption; } set { this.AuthorizationUrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of ClientId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ClientIdOption { get; private set; }

        /// <summary>
        /// The client identifier issued to the application by the OpenID Connect provider. This is used to identify the application during the authentication process.
        /// </summary>
        /// <value>The client identifier issued to the application by the OpenID Connect provider. This is used to identify the application during the authentication process.</value>
        /* <example>123456</example> */
        [JsonPropertyName("ClientId")]
        public string? ClientId { get { return this.ClientIdOption; } set { this.ClientIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ClientSecret
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ClientSecretOption { get; private set; }

        /// <summary>
        /// The client secret issued to the application by the OpenID Connect provider. This is used to authenticate the application when requesting tokens.
        /// </summary>
        /// <value>The client secret issued to the application by the OpenID Connect provider. This is used to authenticate the application when requesting tokens.</value>
        /* <example>654321</example> */
        [JsonPropertyName("ClientSecret")]
        public string? ClientSecret { get { return this.ClientSecretOption; } set { this.ClientSecretOption = new(value); } }

        /// <summary>
        /// Used to track the state of Issuer
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IssuerOption { get; private set; }

        /// <summary>
        /// The issuer identifier for the OpenID Connect provider. This is typically the base URL of the provider and is used to validate tokens.
        /// </summary>
        /// <value>The issuer identifier for the OpenID Connect provider. This is typically the base URL of the provider and is used to validate tokens.</value>
        /* <example>https://exampleIdp.com</example> */
        [JsonPropertyName("Issuer")]
        public string? Issuer { get { return this.IssuerOption; } set { this.IssuerOption = new(value); } }

        /// <summary>
        /// Used to track the state of Scopes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> ScopesOption { get; private set; }

        /// <summary>
        /// The scopes requested by the application during the authentication process. Scopes define the access level and Permissions granted to the application.
        /// </summary>
        /// <value>The scopes requested by the application during the authentication process. Scopes define the access level and Permissions granted to the application.</value>
        /* <example>[&quot;openid&quot;,&quot;email&quot;]</example> */
        [JsonPropertyName("Scopes")]
        public List<string>? Scopes { get { return this.ScopesOption; } set { this.ScopesOption = new(value); } }

        /// <summary>
        /// Used to track the state of TokenAuthMethod
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TokenAuthMethodOption { get; private set; }

        /// <summary>
        /// The method used to authenticate the application when requesting tokens. Common methods include &#x60;client_secret_post&#x60; and &#x60;client_secret_basic&#x60;.
        /// </summary>
        /// <value>The method used to authenticate the application when requesting tokens. Common methods include &#x60;client_secret_post&#x60; and &#x60;client_secret_basic&#x60;.</value>
        /* <example>client_secret_post</example> */
        [JsonPropertyName("TokenAuthMethod")]
        public string? TokenAuthMethod { get { return this.TokenAuthMethodOption; } set { this.TokenAuthMethodOption = new(value); } }

        /// <summary>
        /// Used to track the state of TokenUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TokenUrlOption { get; private set; }

        /// <summary>
        /// The URL to the OpenID Connect provider&#39;s token endpoint. This is where the application exchanges the authorization code for tokens.
        /// </summary>
        /// <value>The URL to the OpenID Connect provider&#39;s token endpoint. This is where the application exchanges the authorization code for tokens.</value>
        /* <example>https://exampleIdp.com/oidc/token</example> */
        [JsonPropertyName("TokenUrl")]
        public string? TokenUrl { get { return this.TokenUrlOption; } set { this.TokenUrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of UserInfoUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UserInfoUrlOption { get; private set; }

        /// <summary>
        /// The URL to the OpenID Connect provider&#39;s UserInfo endpoint.
        /// </summary>
        /// <value>The URL to the OpenID Connect provider&#39;s UserInfo endpoint.</value>
        /* <example>https://exampleIdp.com/oidc/userinfo</example> */
        [JsonPropertyName("UserInfoUrl")]
        public string? UserInfoUrl { get { return this.UserInfoUrlOption; } set { this.UserInfoUrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of UserInfoExtractByIdToken
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> UserInfoExtractByIdTokenOption { get; private set; }

        /// <summary>
        /// Indicates if user info should be extracted by ID token.
        /// </summary>
        /// <value>Indicates if user info should be extracted by ID token.</value>
        [JsonPropertyName("UserInfoExtractByIdToken")]
        public bool? UserInfoExtractByIdToken { get { return this.UserInfoExtractByIdTokenOption; } set { this.UserInfoExtractByIdTokenOption = new(value); } }

        /// <summary>
        /// Used to track the state of JWKSEndpoint
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> JWKSEndpointOption { get; private set; }

        /// <summary>
        /// The JWKS endpoint for verifying the ID token.
        /// </summary>
        /// <value>The JWKS endpoint for verifying the ID token.</value>
        /* <example>https://exampleIdp.com/oidc/jwks</example> */
        [JsonPropertyName("JWKSEndpoint")]
        public string? JWKSEndpoint { get { return this.JWKSEndpointOption; } set { this.JWKSEndpointOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OidcConnectionBase {\n");
            sb.Append("  AuthorizationUrl: ").Append(AuthorizationUrl).Append("\n");
            sb.Append("  ClientId: ").Append(ClientId).Append("\n");
            sb.Append("  ClientSecret: ").Append(ClientSecret).Append("\n");
            sb.Append("  Issuer: ").Append(Issuer).Append("\n");
            sb.Append("  Scopes: ").Append(Scopes).Append("\n");
            sb.Append("  TokenAuthMethod: ").Append(TokenAuthMethod).Append("\n");
            sb.Append("  TokenUrl: ").Append(TokenUrl).Append("\n");
            sb.Append("  UserInfoUrl: ").Append(UserInfoUrl).Append("\n");
            sb.Append("  UserInfoExtractByIdToken: ").Append(UserInfoExtractByIdToken).Append("\n");
            sb.Append("  JWKSEndpoint: ").Append(JWKSEndpoint).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OidcConnectionBase" />
    /// </summary>
    public class OidcConnectionBaseJsonConverter : JsonConverter<OidcConnectionBase>
    {
        /// <summary>
        /// Deserializes json to <see cref="OidcConnectionBase" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OidcConnectionBase Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> authorizationUrl = default;
            Option<string?> clientId = default;
            Option<string?> clientSecret = default;
            Option<string?> issuer = default;
            Option<List<string>?> scopes = default;
            Option<string?> tokenAuthMethod = default;
            Option<string?> tokenUrl = default;
            Option<string?> userInfoUrl = default;
            Option<bool?> userInfoExtractByIdToken = default;
            Option<string?> jWKSEndpoint = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "AuthorizationUrl":
                            authorizationUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "ClientId":
                            clientId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "ClientSecret":
                            clientSecret = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "Issuer":
                            issuer = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "Scopes":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                scopes = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "TokenAuthMethod":
                            tokenAuthMethod = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "TokenUrl":
                            tokenUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "UserInfoUrl":
                            userInfoUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "UserInfoExtractByIdToken":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                userInfoExtractByIdToken = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "JWKSEndpoint":
                            jWKSEndpoint = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (authorizationUrl.IsSet && authorizationUrl.Value == null)
                throw new ArgumentNullException(nameof(authorizationUrl), "Property is not nullable for class OidcConnectionBase.");

            if (clientId.IsSet && clientId.Value == null)
                throw new ArgumentNullException(nameof(clientId), "Property is not nullable for class OidcConnectionBase.");

            if (clientSecret.IsSet && clientSecret.Value == null)
                throw new ArgumentNullException(nameof(clientSecret), "Property is not nullable for class OidcConnectionBase.");

            if (issuer.IsSet && issuer.Value == null)
                throw new ArgumentNullException(nameof(issuer), "Property is not nullable for class OidcConnectionBase.");

            if (scopes.IsSet && scopes.Value == null)
                throw new ArgumentNullException(nameof(scopes), "Property is not nullable for class OidcConnectionBase.");

            if (tokenAuthMethod.IsSet && tokenAuthMethod.Value == null)
                throw new ArgumentNullException(nameof(tokenAuthMethod), "Property is not nullable for class OidcConnectionBase.");

            if (tokenUrl.IsSet && tokenUrl.Value == null)
                throw new ArgumentNullException(nameof(tokenUrl), "Property is not nullable for class OidcConnectionBase.");

            if (userInfoUrl.IsSet && userInfoUrl.Value == null)
                throw new ArgumentNullException(nameof(userInfoUrl), "Property is not nullable for class OidcConnectionBase.");

            if (jWKSEndpoint.IsSet && jWKSEndpoint.Value == null)
                throw new ArgumentNullException(nameof(jWKSEndpoint), "Property is not nullable for class OidcConnectionBase.");

            return new OidcConnectionBase(authorizationUrl, clientId, clientSecret, issuer, scopes, tokenAuthMethod, tokenUrl, userInfoUrl, userInfoExtractByIdToken, jWKSEndpoint);
        }

        /// <summary>
        /// Serializes a <see cref="OidcConnectionBase" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="oidcConnectionBase"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OidcConnectionBase oidcConnectionBase, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, oidcConnectionBase, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OidcConnectionBase" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="oidcConnectionBase"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, OidcConnectionBase oidcConnectionBase, JsonSerializerOptions jsonSerializerOptions)
        {
            if (oidcConnectionBase.AuthorizationUrlOption.IsSet && oidcConnectionBase.AuthorizationUrl == null)
                throw new ArgumentNullException(nameof(oidcConnectionBase.AuthorizationUrl), "Property is required for class OidcConnectionBase.");

            if (oidcConnectionBase.ClientIdOption.IsSet && oidcConnectionBase.ClientId == null)
                throw new ArgumentNullException(nameof(oidcConnectionBase.ClientId), "Property is required for class OidcConnectionBase.");

            if (oidcConnectionBase.ClientSecretOption.IsSet && oidcConnectionBase.ClientSecret == null)
                throw new ArgumentNullException(nameof(oidcConnectionBase.ClientSecret), "Property is required for class OidcConnectionBase.");

            if (oidcConnectionBase.IssuerOption.IsSet && oidcConnectionBase.Issuer == null)
                throw new ArgumentNullException(nameof(oidcConnectionBase.Issuer), "Property is required for class OidcConnectionBase.");

            if (oidcConnectionBase.ScopesOption.IsSet && oidcConnectionBase.Scopes == null)
                throw new ArgumentNullException(nameof(oidcConnectionBase.Scopes), "Property is required for class OidcConnectionBase.");

            if (oidcConnectionBase.TokenAuthMethodOption.IsSet && oidcConnectionBase.TokenAuthMethod == null)
                throw new ArgumentNullException(nameof(oidcConnectionBase.TokenAuthMethod), "Property is required for class OidcConnectionBase.");

            if (oidcConnectionBase.TokenUrlOption.IsSet && oidcConnectionBase.TokenUrl == null)
                throw new ArgumentNullException(nameof(oidcConnectionBase.TokenUrl), "Property is required for class OidcConnectionBase.");

            if (oidcConnectionBase.UserInfoUrlOption.IsSet && oidcConnectionBase.UserInfoUrl == null)
                throw new ArgumentNullException(nameof(oidcConnectionBase.UserInfoUrl), "Property is required for class OidcConnectionBase.");

            if (oidcConnectionBase.JWKSEndpointOption.IsSet && oidcConnectionBase.JWKSEndpoint == null)
                throw new ArgumentNullException(nameof(oidcConnectionBase.JWKSEndpoint), "Property is required for class OidcConnectionBase.");

            if (oidcConnectionBase.AuthorizationUrlOption.IsSet)
                writer.WriteString("AuthorizationUrl", oidcConnectionBase.AuthorizationUrl);

            if (oidcConnectionBase.ClientIdOption.IsSet)
                writer.WriteString("ClientId", oidcConnectionBase.ClientId);

            if (oidcConnectionBase.ClientSecretOption.IsSet)
                writer.WriteString("ClientSecret", oidcConnectionBase.ClientSecret);

            if (oidcConnectionBase.IssuerOption.IsSet)
                writer.WriteString("Issuer", oidcConnectionBase.Issuer);

            if (oidcConnectionBase.ScopesOption.IsSet)
            {
                writer.WritePropertyName("Scopes");
                JsonSerializer.Serialize(writer, oidcConnectionBase.Scopes, jsonSerializerOptions);
            }
            if (oidcConnectionBase.TokenAuthMethodOption.IsSet)
                writer.WriteString("TokenAuthMethod", oidcConnectionBase.TokenAuthMethod);

            if (oidcConnectionBase.TokenUrlOption.IsSet)
                writer.WriteString("TokenUrl", oidcConnectionBase.TokenUrl);

            if (oidcConnectionBase.UserInfoUrlOption.IsSet)
                writer.WriteString("UserInfoUrl", oidcConnectionBase.UserInfoUrl);

            if (oidcConnectionBase.UserInfoExtractByIdTokenOption.IsSet)
                if (oidcConnectionBase.UserInfoExtractByIdTokenOption.Value != null)
                    writer.WriteBoolean("UserInfoExtractByIdToken", oidcConnectionBase.UserInfoExtractByIdTokenOption.Value!.Value);
                else
                    writer.WriteNull("UserInfoExtractByIdToken");

            if (oidcConnectionBase.JWKSEndpointOption.IsSet)
                writer.WriteString("JWKSEndpoint", oidcConnectionBase.JWKSEndpoint);
        }
    }
}
