// <auto-generated>
/*
 * LoginRadius API
 *
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LoginRadius.Sdk.Internal.OpenApi.Client;

namespace LoginRadius.Sdk.Internal.OpenApi.Model
{
    /// <summary>
    /// OIDC Device Code Response
    /// </summary>
    public partial class OIDCDeviceCodeResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OIDCDeviceCodeResponse" /> class.
        /// </summary>
        /// <param name="deviceCode">deviceCode</param>
        /// <param name="expiresIn">expiresIn</param>
        /// <param name="interval">interval</param>
        /// <param name="userCode">userCode</param>
        /// <param name="verificationUri">verificationUri</param>
        /// <param name="verificationUriComplete">verificationUriComplete</param>
        [JsonConstructor]
        public OIDCDeviceCodeResponse(Option<string?> deviceCode = default, Option<int?> expiresIn = default, Option<int?> interval = default, Option<string?> userCode = default, Option<string?> verificationUri = default, Option<string?> verificationUriComplete = default)
        {
            DeviceCodeOption = deviceCode;
            ExpiresInOption = expiresIn;
            IntervalOption = interval;
            UserCodeOption = userCode;
            VerificationUriOption = verificationUri;
            VerificationUriCompleteOption = verificationUriComplete;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of DeviceCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DeviceCodeOption { get; private set; }

        /// <summary>
        /// Gets or Sets DeviceCode
        /// </summary>
        /* <example>device_code</example> */
        [JsonPropertyName("device_code")]
        public string? DeviceCode { get { return this.DeviceCodeOption; } set { this.DeviceCodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExpiresIn
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ExpiresInOption { get; private set; }

        /// <summary>
        /// Gets or Sets ExpiresIn
        /// </summary>
        /* <example>1800</example> */
        [JsonPropertyName("expires_in")]
        public int? ExpiresIn { get { return this.ExpiresInOption; } set { this.ExpiresInOption = new(value); } }

        /// <summary>
        /// Used to track the state of Interval
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> IntervalOption { get; private set; }

        /// <summary>
        /// Gets or Sets Interval
        /// </summary>
        /* <example>5</example> */
        [JsonPropertyName("interval")]
        public int? Interval { get { return this.IntervalOption; } set { this.IntervalOption = new(value); } }

        /// <summary>
        /// Used to track the state of UserCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UserCodeOption { get; private set; }

        /// <summary>
        /// Gets or Sets UserCode
        /// </summary>
        /* <example>user_code</example> */
        [JsonPropertyName("user_code")]
        public string? UserCode { get { return this.UserCodeOption; } set { this.UserCodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of VerificationUri
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> VerificationUriOption { get; private set; }

        /// <summary>
        /// Gets or Sets VerificationUri
        /// </summary>
        /* <example>https://example.com/device/verification</example> */
        [JsonPropertyName("verification_uri")]
        public string? VerificationUri { get { return this.VerificationUriOption; } set { this.VerificationUriOption = new(value); } }

        /// <summary>
        /// Used to track the state of VerificationUriComplete
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> VerificationUriCompleteOption { get; private set; }

        /// <summary>
        /// Gets or Sets VerificationUriComplete
        /// </summary>
        /* <example>https://example.com/device/verification?user_code&#x3D;user_code</example> */
        [JsonPropertyName("verification_uri_complete")]
        public string? VerificationUriComplete { get { return this.VerificationUriCompleteOption; } set { this.VerificationUriCompleteOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OIDCDeviceCodeResponse {\n");
            sb.Append("  DeviceCode: ").Append(DeviceCode).Append("\n");
            sb.Append("  ExpiresIn: ").Append(ExpiresIn).Append("\n");
            sb.Append("  Interval: ").Append(Interval).Append("\n");
            sb.Append("  UserCode: ").Append(UserCode).Append("\n");
            sb.Append("  VerificationUri: ").Append(VerificationUri).Append("\n");
            sb.Append("  VerificationUriComplete: ").Append(VerificationUriComplete).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OIDCDeviceCodeResponse" />
    /// </summary>
    public class OIDCDeviceCodeResponseJsonConverter : JsonConverter<OIDCDeviceCodeResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="OIDCDeviceCodeResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OIDCDeviceCodeResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> deviceCode = default;
            Option<int?> expiresIn = default;
            Option<int?> interval = default;
            Option<string?> userCode = default;
            Option<string?> verificationUri = default;
            Option<string?> verificationUriComplete = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "device_code":
                            deviceCode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "expires_in":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                expiresIn = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "interval":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                interval = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "user_code":
                            userCode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "verification_uri":
                            verificationUri = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "verification_uri_complete":
                            verificationUriComplete = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (deviceCode.IsSet && deviceCode.Value == null)
                throw new ArgumentNullException(nameof(deviceCode), "Property is not nullable for class OIDCDeviceCodeResponse.");

            if (expiresIn.IsSet && expiresIn.Value == null)
                throw new ArgumentNullException(nameof(expiresIn), "Property is not nullable for class OIDCDeviceCodeResponse.");

            if (interval.IsSet && interval.Value == null)
                throw new ArgumentNullException(nameof(interval), "Property is not nullable for class OIDCDeviceCodeResponse.");

            if (userCode.IsSet && userCode.Value == null)
                throw new ArgumentNullException(nameof(userCode), "Property is not nullable for class OIDCDeviceCodeResponse.");

            if (verificationUri.IsSet && verificationUri.Value == null)
                throw new ArgumentNullException(nameof(verificationUri), "Property is not nullable for class OIDCDeviceCodeResponse.");

            if (verificationUriComplete.IsSet && verificationUriComplete.Value == null)
                throw new ArgumentNullException(nameof(verificationUriComplete), "Property is not nullable for class OIDCDeviceCodeResponse.");

            return new OIDCDeviceCodeResponse(deviceCode, expiresIn, interval, userCode, verificationUri, verificationUriComplete);
        }

        /// <summary>
        /// Serializes a <see cref="OIDCDeviceCodeResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="oIDCDeviceCodeResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OIDCDeviceCodeResponse oIDCDeviceCodeResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, oIDCDeviceCodeResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OIDCDeviceCodeResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="oIDCDeviceCodeResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, OIDCDeviceCodeResponse oIDCDeviceCodeResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (oIDCDeviceCodeResponse.DeviceCodeOption.IsSet && oIDCDeviceCodeResponse.DeviceCode == null)
                throw new ArgumentNullException(nameof(oIDCDeviceCodeResponse.DeviceCode), "Property is required for class OIDCDeviceCodeResponse.");

            if (oIDCDeviceCodeResponse.UserCodeOption.IsSet && oIDCDeviceCodeResponse.UserCode == null)
                throw new ArgumentNullException(nameof(oIDCDeviceCodeResponse.UserCode), "Property is required for class OIDCDeviceCodeResponse.");

            if (oIDCDeviceCodeResponse.VerificationUriOption.IsSet && oIDCDeviceCodeResponse.VerificationUri == null)
                throw new ArgumentNullException(nameof(oIDCDeviceCodeResponse.VerificationUri), "Property is required for class OIDCDeviceCodeResponse.");

            if (oIDCDeviceCodeResponse.VerificationUriCompleteOption.IsSet && oIDCDeviceCodeResponse.VerificationUriComplete == null)
                throw new ArgumentNullException(nameof(oIDCDeviceCodeResponse.VerificationUriComplete), "Property is required for class OIDCDeviceCodeResponse.");

            if (oIDCDeviceCodeResponse.DeviceCodeOption.IsSet)
                writer.WriteString("device_code", oIDCDeviceCodeResponse.DeviceCode);

            if (oIDCDeviceCodeResponse.ExpiresInOption.IsSet)
                writer.WriteNumber("expires_in", oIDCDeviceCodeResponse.ExpiresInOption.Value!.Value);

            if (oIDCDeviceCodeResponse.IntervalOption.IsSet)
                writer.WriteNumber("interval", oIDCDeviceCodeResponse.IntervalOption.Value!.Value);

            if (oIDCDeviceCodeResponse.UserCodeOption.IsSet)
                writer.WriteString("user_code", oIDCDeviceCodeResponse.UserCode);

            if (oIDCDeviceCodeResponse.VerificationUriOption.IsSet)
                writer.WriteString("verification_uri", oIDCDeviceCodeResponse.VerificationUri);

            if (oIDCDeviceCodeResponse.VerificationUriCompleteOption.IsSet)
                writer.WriteString("verification_uri_complete", oIDCDeviceCodeResponse.VerificationUriComplete);
        }
    }
}
