// <auto-generated>
/*
 * LoginRadius API
 *
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LoginRadius.Sdk.Internal.OpenApi.Client;

namespace LoginRadius.Sdk.Internal.OpenApi.Model
{
    /// <summary>
    /// OIDC Userinfo request
    /// </summary>
    public partial class OIDCUserinfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OIDCUserinfo" /> class.
        /// </summary>
        /// <param name="accessToken">accessToken</param>
        [JsonConstructor]
        public OIDCUserinfo(string accessToken)
        {
            AccessToken = accessToken;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets AccessToken
        /// </summary>
        /* <example>eyJhbGciOiJIUz...</example> */
        [JsonPropertyName("access_token")]
        public string AccessToken { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OIDCUserinfo {\n");
            sb.Append("  AccessToken: ").Append(AccessToken).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OIDCUserinfo" />
    /// </summary>
    public class OIDCUserinfoJsonConverter : JsonConverter<OIDCUserinfo>
    {
        /// <summary>
        /// Deserializes json to <see cref="OIDCUserinfo" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OIDCUserinfo Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> accessToken = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "access_token":
                            accessToken = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!accessToken.IsSet)
                throw new ArgumentException("Property is required for class OIDCUserinfo.", nameof(accessToken));

            if (accessToken.IsSet && accessToken.Value == null)
                throw new ArgumentNullException(nameof(accessToken), "Property is not nullable for class OIDCUserinfo.");

            return new OIDCUserinfo(accessToken.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="OIDCUserinfo" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="oIDCUserinfo"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OIDCUserinfo oIDCUserinfo, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, oIDCUserinfo, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OIDCUserinfo" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="oIDCUserinfo"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, OIDCUserinfo oIDCUserinfo, JsonSerializerOptions jsonSerializerOptions)
        {
            if (oIDCUserinfo.AccessToken == null)
                throw new ArgumentNullException(nameof(oIDCUserinfo.AccessToken), "Property is required for class OIDCUserinfo.");

            writer.WriteString("access_token", oIDCUserinfo.AccessToken);
        }
    }
}
