// <auto-generated>
/*
 * LoginRadius API
 *
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LoginRadius.Sdk.Internal.OpenApi.Client;

namespace LoginRadius.Sdk.Internal.OpenApi.Model
{
    /// <summary>
    /// OIDCConnectionCreateRequest
    /// </summary>
    public partial class OIDCConnectionCreateRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OIDCConnectionCreateRequest" /> class.
        /// </summary>
        /// <param name="name">Name of the connection</param>
        /// <param name="domain">Domain associated with the connection</param>
        /// <param name="connectionType">Type of the connection, which is OIDC in this case.</param>
        /// <param name="attributes">attributes</param>
        /// <param name="authorizationUrl">The URL to the OpenID Connect provider&#39;s authorization endpoint. This is where users are redirected to authenticate and authorize access.</param>
        /// <param name="clientId">The client identifier issued to the application by the OpenID Connect provider. This is used to identify the application during the authentication process.</param>
        /// <param name="clientSecret">The client secret issued to the application by the OpenID Connect provider. This is used to authenticate the application when requesting tokens.</param>
        /// <param name="issuer">The issuer identifier for the OpenID Connect provider. This is typically the base URL of the provider and is used to validate tokens.</param>
        /// <param name="scopes">The scopes requested by the application during the authentication process. Scopes define the access level and Permissions granted to the application.</param>
        /// <param name="tokenAuthMethod">The method used to authenticate the application when requesting tokens. Common methods include &#x60;client_secret_post&#x60; and &#x60;client_secret_basic&#x60;.</param>
        /// <param name="tokenUrl">The URL to the OpenID Connect provider&#39;s token endpoint. This is where the application exchanges the authorization code for tokens.</param>
        /// <param name="userInfoUrl">The URL to the OpenID Connect provider&#39;s UserInfo endpoint.</param>
        /// <param name="userInfoExtractByIdToken">Indicates if user info should be extracted by ID token.</param>
        /// <param name="jWKSEndpoint">The JWKS endpoint for verifying the ID token.</param>
        [JsonConstructor]
        public OIDCConnectionCreateRequest(string name, string domain, ConnectionTypeEnum connectionType, Option<OrganizationsConnectionBaseAttributes?> attributes = default, Option<string?> authorizationUrl = default, Option<string?> clientId = default, Option<string?> clientSecret = default, Option<string?> issuer = default, Option<List<string>?> scopes = default, Option<string?> tokenAuthMethod = default, Option<string?> tokenUrl = default, Option<string?> userInfoUrl = default, Option<bool?> userInfoExtractByIdToken = default, Option<string?> jWKSEndpoint = default)
        {
            Name = name;
            Domain = domain;
            ConnectionType = connectionType;
            AttributesOption = attributes;
            AuthorizationUrlOption = authorizationUrl;
            ClientIdOption = clientId;
            ClientSecretOption = clientSecret;
            IssuerOption = issuer;
            ScopesOption = scopes;
            TokenAuthMethodOption = tokenAuthMethod;
            TokenUrlOption = tokenUrl;
            UserInfoUrlOption = userInfoUrl;
            UserInfoExtractByIdTokenOption = userInfoExtractByIdToken;
            JWKSEndpointOption = jWKSEndpoint;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Type of the connection, which is OIDC in this case.
        /// </summary>
        /// <value>Type of the connection, which is OIDC in this case.</value>
        public enum ConnectionTypeEnum
        {
            /// <summary>
            /// Enum OidcCustom for value: oidc_custom
            /// </summary>
            OidcCustom = 1
        }

        /// <summary>
        /// Returns a <see cref="ConnectionTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ConnectionTypeEnum ConnectionTypeEnumFromString(string value)
        {
            if (value.Equals("oidc_custom"))
                return ConnectionTypeEnum.OidcCustom;

            throw new NotImplementedException($"Could not convert value to type ConnectionTypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ConnectionTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ConnectionTypeEnum? ConnectionTypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("oidc_custom"))
                return ConnectionTypeEnum.OidcCustom;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ConnectionTypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ConnectionTypeEnumToJsonValue(ConnectionTypeEnum value)
        {
            if (value == ConnectionTypeEnum.OidcCustom)
                return "oidc_custom";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Type of the connection, which is OIDC in this case.
        /// </summary>
        /// <value>Type of the connection, which is OIDC in this case.</value>
        /* <example>oidc_custom</example> */
        [JsonPropertyName("ConnectionType")]
        public ConnectionTypeEnum ConnectionType { get; set; }

        /// <summary>
        /// Name of the connection
        /// </summary>
        /// <value>Name of the connection</value>
        /* <example>AzureAD</example> */
        [JsonPropertyName("Name")]
        public string Name { get; set; }

        /// <summary>
        /// Domain associated with the connection
        /// </summary>
        /// <value>Domain associated with the connection</value>
        /* <example>example.com</example> */
        [JsonPropertyName("Domain")]
        public string Domain { get; set; }

        /// <summary>
        /// Used to track the state of Attributes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<OrganizationsConnectionBaseAttributes?> AttributesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Attributes
        /// </summary>
        [JsonPropertyName("Attributes")]
        public OrganizationsConnectionBaseAttributes? Attributes { get { return this.AttributesOption; } set { this.AttributesOption = new(value); } }

        /// <summary>
        /// Used to track the state of AuthorizationUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AuthorizationUrlOption { get; private set; }

        /// <summary>
        /// The URL to the OpenID Connect provider&#39;s authorization endpoint. This is where users are redirected to authenticate and authorize access.
        /// </summary>
        /// <value>The URL to the OpenID Connect provider&#39;s authorization endpoint. This is where users are redirected to authenticate and authorize access.</value>
        /* <example>https://exampleIdp.com/oidc/authorize</example> */
        [JsonPropertyName("AuthorizationUrl")]
        public string? AuthorizationUrl { get { return this.AuthorizationUrlOption; } set { this.AuthorizationUrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of ClientId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ClientIdOption { get; private set; }

        /// <summary>
        /// The client identifier issued to the application by the OpenID Connect provider. This is used to identify the application during the authentication process.
        /// </summary>
        /// <value>The client identifier issued to the application by the OpenID Connect provider. This is used to identify the application during the authentication process.</value>
        /* <example>123456</example> */
        [JsonPropertyName("ClientId")]
        public string? ClientId { get { return this.ClientIdOption; } set { this.ClientIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ClientSecret
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ClientSecretOption { get; private set; }

        /// <summary>
        /// The client secret issued to the application by the OpenID Connect provider. This is used to authenticate the application when requesting tokens.
        /// </summary>
        /// <value>The client secret issued to the application by the OpenID Connect provider. This is used to authenticate the application when requesting tokens.</value>
        /* <example>654321</example> */
        [JsonPropertyName("ClientSecret")]
        public string? ClientSecret { get { return this.ClientSecretOption; } set { this.ClientSecretOption = new(value); } }

        /// <summary>
        /// Used to track the state of Issuer
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IssuerOption { get; private set; }

        /// <summary>
        /// The issuer identifier for the OpenID Connect provider. This is typically the base URL of the provider and is used to validate tokens.
        /// </summary>
        /// <value>The issuer identifier for the OpenID Connect provider. This is typically the base URL of the provider and is used to validate tokens.</value>
        /* <example>https://exampleIdp.com</example> */
        [JsonPropertyName("Issuer")]
        public string? Issuer { get { return this.IssuerOption; } set { this.IssuerOption = new(value); } }

        /// <summary>
        /// Used to track the state of Scopes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> ScopesOption { get; private set; }

        /// <summary>
        /// The scopes requested by the application during the authentication process. Scopes define the access level and Permissions granted to the application.
        /// </summary>
        /// <value>The scopes requested by the application during the authentication process. Scopes define the access level and Permissions granted to the application.</value>
        /* <example>[openid, email]</example> */
        [JsonPropertyName("Scopes")]
        public List<string>? Scopes { get { return this.ScopesOption; } set { this.ScopesOption = new(value); } }

        /// <summary>
        /// Used to track the state of TokenAuthMethod
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TokenAuthMethodOption { get; private set; }

        /// <summary>
        /// The method used to authenticate the application when requesting tokens. Common methods include &#x60;client_secret_post&#x60; and &#x60;client_secret_basic&#x60;.
        /// </summary>
        /// <value>The method used to authenticate the application when requesting tokens. Common methods include &#x60;client_secret_post&#x60; and &#x60;client_secret_basic&#x60;.</value>
        /* <example>client_secret_post</example> */
        [JsonPropertyName("TokenAuthMethod")]
        public string? TokenAuthMethod { get { return this.TokenAuthMethodOption; } set { this.TokenAuthMethodOption = new(value); } }

        /// <summary>
        /// Used to track the state of TokenUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TokenUrlOption { get; private set; }

        /// <summary>
        /// The URL to the OpenID Connect provider&#39;s token endpoint. This is where the application exchanges the authorization code for tokens.
        /// </summary>
        /// <value>The URL to the OpenID Connect provider&#39;s token endpoint. This is where the application exchanges the authorization code for tokens.</value>
        /* <example>https://exampleIdp.com/oidc/token</example> */
        [JsonPropertyName("TokenUrl")]
        public string? TokenUrl { get { return this.TokenUrlOption; } set { this.TokenUrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of UserInfoUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UserInfoUrlOption { get; private set; }

        /// <summary>
        /// The URL to the OpenID Connect provider&#39;s UserInfo endpoint.
        /// </summary>
        /// <value>The URL to the OpenID Connect provider&#39;s UserInfo endpoint.</value>
        /* <example>https://exampleIdp.com/oidc/userinfo</example> */
        [JsonPropertyName("UserInfoUrl")]
        public string? UserInfoUrl { get { return this.UserInfoUrlOption; } set { this.UserInfoUrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of UserInfoExtractByIdToken
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> UserInfoExtractByIdTokenOption { get; private set; }

        /// <summary>
        /// Indicates if user info should be extracted by ID token.
        /// </summary>
        /// <value>Indicates if user info should be extracted by ID token.</value>
        [JsonPropertyName("UserInfoExtractByIdToken")]
        public bool? UserInfoExtractByIdToken { get { return this.UserInfoExtractByIdTokenOption; } set { this.UserInfoExtractByIdTokenOption = new(value); } }

        /// <summary>
        /// Used to track the state of JWKSEndpoint
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> JWKSEndpointOption { get; private set; }

        /// <summary>
        /// The JWKS endpoint for verifying the ID token.
        /// </summary>
        /// <value>The JWKS endpoint for verifying the ID token.</value>
        /* <example>https://exampleIdp.com/oidc/jwks</example> */
        [JsonPropertyName("JWKSEndpoint")]
        public string? JWKSEndpoint { get { return this.JWKSEndpointOption; } set { this.JWKSEndpointOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OIDCConnectionCreateRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Domain: ").Append(Domain).Append("\n");
            sb.Append("  ConnectionType: ").Append(ConnectionType).Append("\n");
            sb.Append("  Attributes: ").Append(Attributes).Append("\n");
            sb.Append("  AuthorizationUrl: ").Append(AuthorizationUrl).Append("\n");
            sb.Append("  ClientId: ").Append(ClientId).Append("\n");
            sb.Append("  ClientSecret: ").Append(ClientSecret).Append("\n");
            sb.Append("  Issuer: ").Append(Issuer).Append("\n");
            sb.Append("  Scopes: ").Append(Scopes).Append("\n");
            sb.Append("  TokenAuthMethod: ").Append(TokenAuthMethod).Append("\n");
            sb.Append("  TokenUrl: ").Append(TokenUrl).Append("\n");
            sb.Append("  UserInfoUrl: ").Append(UserInfoUrl).Append("\n");
            sb.Append("  UserInfoExtractByIdToken: ").Append(UserInfoExtractByIdToken).Append("\n");
            sb.Append("  JWKSEndpoint: ").Append(JWKSEndpoint).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OIDCConnectionCreateRequest" />
    /// </summary>
    public class OIDCConnectionCreateRequestJsonConverter : JsonConverter<OIDCConnectionCreateRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="OIDCConnectionCreateRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OIDCConnectionCreateRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> domain = default;
            Option<OIDCConnectionCreateRequest.ConnectionTypeEnum?> connectionType = default;
            Option<OrganizationsConnectionBaseAttributes?> attributes = default;
            Option<string?> authorizationUrl = default;
            Option<string?> clientId = default;
            Option<string?> clientSecret = default;
            Option<string?> issuer = default;
            Option<List<string>?> scopes = default;
            Option<string?> tokenAuthMethod = default;
            Option<string?> tokenUrl = default;
            Option<string?> userInfoUrl = default;
            Option<bool?> userInfoExtractByIdToken = default;
            Option<string?> jWKSEndpoint = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "Name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "Domain":
                            domain = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "ConnectionType":
                            string? connectionTypeRawValue = utf8JsonReader.GetString();
                            if (connectionTypeRawValue != null)
                                connectionType = new Option<OIDCConnectionCreateRequest.ConnectionTypeEnum?>(OIDCConnectionCreateRequest.ConnectionTypeEnumFromStringOrDefault(connectionTypeRawValue));
                            break;
                        case "Attributes":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                attributes = new Option<OrganizationsConnectionBaseAttributes?>(JsonSerializer.Deserialize<OrganizationsConnectionBaseAttributes>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "AuthorizationUrl":
                            authorizationUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "ClientId":
                            clientId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "ClientSecret":
                            clientSecret = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "Issuer":
                            issuer = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "Scopes":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                scopes = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "TokenAuthMethod":
                            tokenAuthMethod = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "TokenUrl":
                            tokenUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "UserInfoUrl":
                            userInfoUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "UserInfoExtractByIdToken":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                userInfoExtractByIdToken = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "JWKSEndpoint":
                            jWKSEndpoint = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class OIDCConnectionCreateRequest.", nameof(name));

            if (!domain.IsSet)
                throw new ArgumentException("Property is required for class OIDCConnectionCreateRequest.", nameof(domain));

            if (!connectionType.IsSet)
                throw new ArgumentException("Property is required for class OIDCConnectionCreateRequest.", nameof(connectionType));

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class OIDCConnectionCreateRequest.");

            if (domain.IsSet && domain.Value == null)
                throw new ArgumentNullException(nameof(domain), "Property is not nullable for class OIDCConnectionCreateRequest.");

            if (connectionType.IsSet && connectionType.Value == null)
                throw new ArgumentNullException(nameof(connectionType), "Property is not nullable for class OIDCConnectionCreateRequest.");

            if (attributes.IsSet && attributes.Value == null)
                throw new ArgumentNullException(nameof(attributes), "Property is not nullable for class OIDCConnectionCreateRequest.");

            if (authorizationUrl.IsSet && authorizationUrl.Value == null)
                throw new ArgumentNullException(nameof(authorizationUrl), "Property is not nullable for class OIDCConnectionCreateRequest.");

            if (clientId.IsSet && clientId.Value == null)
                throw new ArgumentNullException(nameof(clientId), "Property is not nullable for class OIDCConnectionCreateRequest.");

            if (clientSecret.IsSet && clientSecret.Value == null)
                throw new ArgumentNullException(nameof(clientSecret), "Property is not nullable for class OIDCConnectionCreateRequest.");

            if (issuer.IsSet && issuer.Value == null)
                throw new ArgumentNullException(nameof(issuer), "Property is not nullable for class OIDCConnectionCreateRequest.");

            if (scopes.IsSet && scopes.Value == null)
                throw new ArgumentNullException(nameof(scopes), "Property is not nullable for class OIDCConnectionCreateRequest.");

            if (tokenAuthMethod.IsSet && tokenAuthMethod.Value == null)
                throw new ArgumentNullException(nameof(tokenAuthMethod), "Property is not nullable for class OIDCConnectionCreateRequest.");

            if (tokenUrl.IsSet && tokenUrl.Value == null)
                throw new ArgumentNullException(nameof(tokenUrl), "Property is not nullable for class OIDCConnectionCreateRequest.");

            if (userInfoUrl.IsSet && userInfoUrl.Value == null)
                throw new ArgumentNullException(nameof(userInfoUrl), "Property is not nullable for class OIDCConnectionCreateRequest.");

            if (jWKSEndpoint.IsSet && jWKSEndpoint.Value == null)
                throw new ArgumentNullException(nameof(jWKSEndpoint), "Property is not nullable for class OIDCConnectionCreateRequest.");

            return new OIDCConnectionCreateRequest(name.Value!, domain.Value!, connectionType.Value!.Value!, attributes, authorizationUrl, clientId, clientSecret, issuer, scopes, tokenAuthMethod, tokenUrl, userInfoUrl, userInfoExtractByIdToken, jWKSEndpoint);
        }

        /// <summary>
        /// Serializes a <see cref="OIDCConnectionCreateRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="oIDCConnectionCreateRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OIDCConnectionCreateRequest oIDCConnectionCreateRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, oIDCConnectionCreateRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OIDCConnectionCreateRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="oIDCConnectionCreateRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, OIDCConnectionCreateRequest oIDCConnectionCreateRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (oIDCConnectionCreateRequest.Name == null)
                throw new ArgumentNullException(nameof(oIDCConnectionCreateRequest.Name), "Property is required for class OIDCConnectionCreateRequest.");

            if (oIDCConnectionCreateRequest.Domain == null)
                throw new ArgumentNullException(nameof(oIDCConnectionCreateRequest.Domain), "Property is required for class OIDCConnectionCreateRequest.");

            if (oIDCConnectionCreateRequest.AttributesOption.IsSet && oIDCConnectionCreateRequest.Attributes == null)
                throw new ArgumentNullException(nameof(oIDCConnectionCreateRequest.Attributes), "Property is required for class OIDCConnectionCreateRequest.");

            if (oIDCConnectionCreateRequest.AuthorizationUrlOption.IsSet && oIDCConnectionCreateRequest.AuthorizationUrl == null)
                throw new ArgumentNullException(nameof(oIDCConnectionCreateRequest.AuthorizationUrl), "Property is required for class OIDCConnectionCreateRequest.");

            if (oIDCConnectionCreateRequest.ClientIdOption.IsSet && oIDCConnectionCreateRequest.ClientId == null)
                throw new ArgumentNullException(nameof(oIDCConnectionCreateRequest.ClientId), "Property is required for class OIDCConnectionCreateRequest.");

            if (oIDCConnectionCreateRequest.ClientSecretOption.IsSet && oIDCConnectionCreateRequest.ClientSecret == null)
                throw new ArgumentNullException(nameof(oIDCConnectionCreateRequest.ClientSecret), "Property is required for class OIDCConnectionCreateRequest.");

            if (oIDCConnectionCreateRequest.IssuerOption.IsSet && oIDCConnectionCreateRequest.Issuer == null)
                throw new ArgumentNullException(nameof(oIDCConnectionCreateRequest.Issuer), "Property is required for class OIDCConnectionCreateRequest.");

            if (oIDCConnectionCreateRequest.ScopesOption.IsSet && oIDCConnectionCreateRequest.Scopes == null)
                throw new ArgumentNullException(nameof(oIDCConnectionCreateRequest.Scopes), "Property is required for class OIDCConnectionCreateRequest.");

            if (oIDCConnectionCreateRequest.TokenAuthMethodOption.IsSet && oIDCConnectionCreateRequest.TokenAuthMethod == null)
                throw new ArgumentNullException(nameof(oIDCConnectionCreateRequest.TokenAuthMethod), "Property is required for class OIDCConnectionCreateRequest.");

            if (oIDCConnectionCreateRequest.TokenUrlOption.IsSet && oIDCConnectionCreateRequest.TokenUrl == null)
                throw new ArgumentNullException(nameof(oIDCConnectionCreateRequest.TokenUrl), "Property is required for class OIDCConnectionCreateRequest.");

            if (oIDCConnectionCreateRequest.UserInfoUrlOption.IsSet && oIDCConnectionCreateRequest.UserInfoUrl == null)
                throw new ArgumentNullException(nameof(oIDCConnectionCreateRequest.UserInfoUrl), "Property is required for class OIDCConnectionCreateRequest.");

            if (oIDCConnectionCreateRequest.JWKSEndpointOption.IsSet && oIDCConnectionCreateRequest.JWKSEndpoint == null)
                throw new ArgumentNullException(nameof(oIDCConnectionCreateRequest.JWKSEndpoint), "Property is required for class OIDCConnectionCreateRequest.");

            writer.WriteString("Name", oIDCConnectionCreateRequest.Name);

            writer.WriteString("Domain", oIDCConnectionCreateRequest.Domain);

            var connectionTypeRawValue = OIDCConnectionCreateRequest.ConnectionTypeEnumToJsonValue(oIDCConnectionCreateRequest.ConnectionType);
            writer.WriteString("ConnectionType", connectionTypeRawValue);
            if (oIDCConnectionCreateRequest.AttributesOption.IsSet)
            {
                writer.WritePropertyName("Attributes");
                JsonSerializer.Serialize(writer, oIDCConnectionCreateRequest.Attributes, jsonSerializerOptions);
            }
            if (oIDCConnectionCreateRequest.AuthorizationUrlOption.IsSet)
                writer.WriteString("AuthorizationUrl", oIDCConnectionCreateRequest.AuthorizationUrl);

            if (oIDCConnectionCreateRequest.ClientIdOption.IsSet)
                writer.WriteString("ClientId", oIDCConnectionCreateRequest.ClientId);

            if (oIDCConnectionCreateRequest.ClientSecretOption.IsSet)
                writer.WriteString("ClientSecret", oIDCConnectionCreateRequest.ClientSecret);

            if (oIDCConnectionCreateRequest.IssuerOption.IsSet)
                writer.WriteString("Issuer", oIDCConnectionCreateRequest.Issuer);

            if (oIDCConnectionCreateRequest.ScopesOption.IsSet)
            {
                writer.WritePropertyName("Scopes");
                JsonSerializer.Serialize(writer, oIDCConnectionCreateRequest.Scopes, jsonSerializerOptions);
            }
            if (oIDCConnectionCreateRequest.TokenAuthMethodOption.IsSet)
                writer.WriteString("TokenAuthMethod", oIDCConnectionCreateRequest.TokenAuthMethod);

            if (oIDCConnectionCreateRequest.TokenUrlOption.IsSet)
                writer.WriteString("TokenUrl", oIDCConnectionCreateRequest.TokenUrl);

            if (oIDCConnectionCreateRequest.UserInfoUrlOption.IsSet)
                writer.WriteString("UserInfoUrl", oIDCConnectionCreateRequest.UserInfoUrl);

            if (oIDCConnectionCreateRequest.UserInfoExtractByIdTokenOption.IsSet)
                if (oIDCConnectionCreateRequest.UserInfoExtractByIdTokenOption.Value != null)
                    writer.WriteBoolean("UserInfoExtractByIdToken", oIDCConnectionCreateRequest.UserInfoExtractByIdTokenOption.Value!.Value);
                else
                    writer.WriteNull("UserInfoExtractByIdToken");

            if (oIDCConnectionCreateRequest.JWKSEndpointOption.IsSet)
                writer.WriteString("JWKSEndpoint", oIDCConnectionCreateRequest.JWKSEndpoint);
        }
    }
}
