// <auto-generated>
/*
 * LoginRadius API
 *
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LoginRadius.Sdk.Internal.OpenApi.Client;

namespace LoginRadius.Sdk.Internal.OpenApi.Model
{
    /// <summary>
    /// Just-In-Time (JIT) provisioning policy for the organization
    /// </summary>
    public partial class OrganizationsPolicyBaseJITPolicy : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrganizationsPolicyBaseJITPolicy" /> class.
        /// </summary>
        /// <param name="enabled">Indicates if JIT provisioning is enabled</param>
        [JsonConstructor]
        public OrganizationsPolicyBaseJITPolicy(Option<bool?> enabled = default)
        {
            EnabledOption = enabled;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Enabled
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> EnabledOption { get; private set; }

        /// <summary>
        /// Indicates if JIT provisioning is enabled
        /// </summary>
        /// <value>Indicates if JIT provisioning is enabled</value>
        /* <example>false</example> */
        [JsonPropertyName("Enabled")]
        public bool? Enabled { get { return this.EnabledOption; } set { this.EnabledOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrganizationsPolicyBaseJITPolicy {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OrganizationsPolicyBaseJITPolicy" />
    /// </summary>
    public class OrganizationsPolicyBaseJITPolicyJsonConverter : JsonConverter<OrganizationsPolicyBaseJITPolicy>
    {
        /// <summary>
        /// Deserializes json to <see cref="OrganizationsPolicyBaseJITPolicy" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OrganizationsPolicyBaseJITPolicy Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> enabled = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "Enabled":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                enabled = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            return new OrganizationsPolicyBaseJITPolicy(enabled);
        }

        /// <summary>
        /// Serializes a <see cref="OrganizationsPolicyBaseJITPolicy" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="organizationsPolicyBaseJITPolicy"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OrganizationsPolicyBaseJITPolicy organizationsPolicyBaseJITPolicy, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, organizationsPolicyBaseJITPolicy, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OrganizationsPolicyBaseJITPolicy" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="organizationsPolicyBaseJITPolicy"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, OrganizationsPolicyBaseJITPolicy organizationsPolicyBaseJITPolicy, JsonSerializerOptions jsonSerializerOptions)
        {
            if (organizationsPolicyBaseJITPolicy.EnabledOption.IsSet)
                if (organizationsPolicyBaseJITPolicy.EnabledOption.Value != null)
                    writer.WriteBoolean("Enabled", organizationsPolicyBaseJITPolicy.EnabledOption.Value!.Value);
                else
                    writer.WriteNull("Enabled");
        }
    }
}
