// <auto-generated>
/*
 * LoginRadius API
 *
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LoginRadius.Sdk.Internal.OpenApi.Client;

namespace LoginRadius.Sdk.Internal.OpenApi.Model
{
    /// <summary>
    /// PasswordLessUserNameOTPModelCore
    /// </summary>
    public partial class PasswordLessUserNameOTPModelCore : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PasswordLessUserNameOTPModelCore" /> class.
        /// </summary>
        /// <param name="otp">The one-time Password (OTP) for verification.</param>
        /// <param name="userName">The Username associated with the Account.</param>
        /// <param name="securityAnswer">The security answers which is set for the User, this will be used when the User is blocked for the security question.</param>
        /// <param name="welcomeEmailTemplate">The template for the welcome Email.</param>
        [JsonConstructor]
        public PasswordLessUserNameOTPModelCore(string otp, string userName, Option<Dictionary<string, string>?> securityAnswer = default, Option<string?> welcomeEmailTemplate = default)
        {
            Otp = otp;
            UserName = userName;
            SecurityAnswerOption = securityAnswer;
            WelcomeEmailTemplateOption = welcomeEmailTemplate;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The one-time Password (OTP) for verification.
        /// </summary>
        /// <value>The one-time Password (OTP) for verification.</value>
        /* <example>123456</example> */
        [JsonPropertyName("Otp")]
        public string Otp { get; set; }

        /// <summary>
        /// The Username associated with the Account.
        /// </summary>
        /// <value>The Username associated with the Account.</value>
        /* <example>john_doe</example> */
        [JsonPropertyName("UserName")]
        public string UserName { get; set; }

        /// <summary>
        /// Used to track the state of SecurityAnswer
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, string>?> SecurityAnswerOption { get; private set; }

        /// <summary>
        /// The security answers which is set for the User, this will be used when the User is blocked for the security question.
        /// </summary>
        /// <value>The security answers which is set for the User, this will be used when the User is blocked for the security question.</value>
        [JsonPropertyName("SecurityAnswer")]
        public Dictionary<string, string>? SecurityAnswer { get { return this.SecurityAnswerOption; } set { this.SecurityAnswerOption = new(value); } }

        /// <summary>
        /// Used to track the state of WelcomeEmailTemplate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> WelcomeEmailTemplateOption { get; private set; }

        /// <summary>
        /// The template for the welcome Email.
        /// </summary>
        /// <value>The template for the welcome Email.</value>
        /* <example>WelcomeTemplate</example> */
        [JsonPropertyName("WelcomeEmailTemplate")]
        public string? WelcomeEmailTemplate { get { return this.WelcomeEmailTemplateOption; } set { this.WelcomeEmailTemplateOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PasswordLessUserNameOTPModelCore {\n");
            sb.Append("  Otp: ").Append(Otp).Append("\n");
            sb.Append("  UserName: ").Append(UserName).Append("\n");
            sb.Append("  SecurityAnswer: ").Append(SecurityAnswer).Append("\n");
            sb.Append("  WelcomeEmailTemplate: ").Append(WelcomeEmailTemplate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PasswordLessUserNameOTPModelCore" />
    /// </summary>
    public class PasswordLessUserNameOTPModelCoreJsonConverter : JsonConverter<PasswordLessUserNameOTPModelCore>
    {
        /// <summary>
        /// Deserializes json to <see cref="PasswordLessUserNameOTPModelCore" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PasswordLessUserNameOTPModelCore Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> otp = default;
            Option<string?> userName = default;
            Option<Dictionary<string, string>?> securityAnswer = default;
            Option<string?> welcomeEmailTemplate = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "Otp":
                            otp = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "UserName":
                            userName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "SecurityAnswer":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                securityAnswer = new Option<Dictionary<string, string>?>(JsonSerializer.Deserialize<Dictionary<string, string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "WelcomeEmailTemplate":
                            welcomeEmailTemplate = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!otp.IsSet)
                throw new ArgumentException("Property is required for class PasswordLessUserNameOTPModelCore.", nameof(otp));

            if (!userName.IsSet)
                throw new ArgumentException("Property is required for class PasswordLessUserNameOTPModelCore.", nameof(userName));

            if (otp.IsSet && otp.Value == null)
                throw new ArgumentNullException(nameof(otp), "Property is not nullable for class PasswordLessUserNameOTPModelCore.");

            if (userName.IsSet && userName.Value == null)
                throw new ArgumentNullException(nameof(userName), "Property is not nullable for class PasswordLessUserNameOTPModelCore.");

            if (welcomeEmailTemplate.IsSet && welcomeEmailTemplate.Value == null)
                throw new ArgumentNullException(nameof(welcomeEmailTemplate), "Property is not nullable for class PasswordLessUserNameOTPModelCore.");

            return new PasswordLessUserNameOTPModelCore(otp.Value!, userName.Value!, securityAnswer, welcomeEmailTemplate);
        }

        /// <summary>
        /// Serializes a <see cref="PasswordLessUserNameOTPModelCore" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="passwordLessUserNameOTPModelCore"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PasswordLessUserNameOTPModelCore passwordLessUserNameOTPModelCore, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, passwordLessUserNameOTPModelCore, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PasswordLessUserNameOTPModelCore" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="passwordLessUserNameOTPModelCore"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PasswordLessUserNameOTPModelCore passwordLessUserNameOTPModelCore, JsonSerializerOptions jsonSerializerOptions)
        {
            if (passwordLessUserNameOTPModelCore.Otp == null)
                throw new ArgumentNullException(nameof(passwordLessUserNameOTPModelCore.Otp), "Property is required for class PasswordLessUserNameOTPModelCore.");

            if (passwordLessUserNameOTPModelCore.UserName == null)
                throw new ArgumentNullException(nameof(passwordLessUserNameOTPModelCore.UserName), "Property is required for class PasswordLessUserNameOTPModelCore.");

            if (passwordLessUserNameOTPModelCore.WelcomeEmailTemplateOption.IsSet && passwordLessUserNameOTPModelCore.WelcomeEmailTemplate == null)
                throw new ArgumentNullException(nameof(passwordLessUserNameOTPModelCore.WelcomeEmailTemplate), "Property is required for class PasswordLessUserNameOTPModelCore.");

            writer.WriteString("Otp", passwordLessUserNameOTPModelCore.Otp);

            writer.WriteString("UserName", passwordLessUserNameOTPModelCore.UserName);

            if (passwordLessUserNameOTPModelCore.SecurityAnswerOption.IsSet)
                if (passwordLessUserNameOTPModelCore.SecurityAnswerOption.Value != null)
                {
                    writer.WritePropertyName("SecurityAnswer");
                    JsonSerializer.Serialize(writer, passwordLessUserNameOTPModelCore.SecurityAnswer, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("SecurityAnswer");
            if (passwordLessUserNameOTPModelCore.WelcomeEmailTemplateOption.IsSet)
                writer.WriteString("WelcomeEmailTemplate", passwordLessUserNameOTPModelCore.WelcomeEmailTemplate);
        }
    }
}
