// <auto-generated>
/*
 * LoginRadius API
 *
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LoginRadius.Sdk.Internal.OpenApi.Client;

namespace LoginRadius.Sdk.Internal.OpenApi.Model
{
    /// <summary>
    /// PasswordLessUserNameOTPModel
    /// </summary>
    public partial class PasswordLessUserNameOTPModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PasswordLessUserNameOTPModel" /> class.
        /// </summary>
        /// <param name="otp">The one-time Password (OTP) for verification.</param>
        /// <param name="userName">The Username associated with the Account.</param>
        /// <param name="gRecaptchaResponse">The Google reCAPTCHA response which is sent to the server for verification.</param>
        /// <param name="qqCaptchaTicket">The QQ Captcha ticket which is sent to the server for verification.</param>
        /// <param name="qqCaptchaRandstr">The QQ Captcha random string which is sent to the server for verification.</param>
        /// <param name="hCaptchaResponse">The hCaptcha response which is sent to the server for verification.</param>
        /// <param name="securityAnswer">The security answers which is set for the User, this will be used when the User is blocked for the security question.</param>
        /// <param name="welcomeEmailTemplate">The template for the welcome Email.</param>
        [JsonConstructor]
        public PasswordLessUserNameOTPModel(string otp, string userName, Option<string?> gRecaptchaResponse = default, Option<string?> qqCaptchaTicket = default, Option<string?> qqCaptchaRandstr = default, Option<string?> hCaptchaResponse = default, Option<Dictionary<string, string>?> securityAnswer = default, Option<string?> welcomeEmailTemplate = default)
        {
            Otp = otp;
            UserName = userName;
            GRecaptchaResponseOption = gRecaptchaResponse;
            QqCaptchaTicketOption = qqCaptchaTicket;
            QqCaptchaRandstrOption = qqCaptchaRandstr;
            HCaptchaResponseOption = hCaptchaResponse;
            SecurityAnswerOption = securityAnswer;
            WelcomeEmailTemplateOption = welcomeEmailTemplate;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The one-time Password (OTP) for verification.
        /// </summary>
        /// <value>The one-time Password (OTP) for verification.</value>
        /* <example>123456</example> */
        [JsonPropertyName("Otp")]
        public string Otp { get; set; }

        /// <summary>
        /// The Username associated with the Account.
        /// </summary>
        /// <value>The Username associated with the Account.</value>
        /* <example>john_doe</example> */
        [JsonPropertyName("UserName")]
        public string UserName { get; set; }

        /// <summary>
        /// Used to track the state of GRecaptchaResponse
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> GRecaptchaResponseOption { get; private set; }

        /// <summary>
        /// The Google reCAPTCHA response which is sent to the server for verification.
        /// </summary>
        /// <value>The Google reCAPTCHA response which is sent to the server for verification.</value>
        /* <example>03AGdBq24...</example> */
        [JsonPropertyName("g-recaptcha-response")]
        public string? GRecaptchaResponse { get { return this.GRecaptchaResponseOption; } set { this.GRecaptchaResponseOption = new(value); } }

        /// <summary>
        /// Used to track the state of QqCaptchaTicket
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> QqCaptchaTicketOption { get; private set; }

        /// <summary>
        /// The QQ Captcha ticket which is sent to the server for verification.
        /// </summary>
        /// <value>The QQ Captcha ticket which is sent to the server for verification.</value>
        /* <example>03AGdBq24...</example> */
        [JsonPropertyName("qq_captcha_ticket")]
        public string? QqCaptchaTicket { get { return this.QqCaptchaTicketOption; } set { this.QqCaptchaTicketOption = new(value); } }

        /// <summary>
        /// Used to track the state of QqCaptchaRandstr
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> QqCaptchaRandstrOption { get; private set; }

        /// <summary>
        /// The QQ Captcha random string which is sent to the server for verification.
        /// </summary>
        /// <value>The QQ Captcha random string which is sent to the server for verification.</value>
        /* <example>03AGdBq24...</example> */
        [JsonPropertyName("qq_captcha_randstr")]
        public string? QqCaptchaRandstr { get { return this.QqCaptchaRandstrOption; } set { this.QqCaptchaRandstrOption = new(value); } }

        /// <summary>
        /// Used to track the state of HCaptchaResponse
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> HCaptchaResponseOption { get; private set; }

        /// <summary>
        /// The hCaptcha response which is sent to the server for verification.
        /// </summary>
        /// <value>The hCaptcha response which is sent to the server for verification.</value>
        /* <example>03AGdBq24...</example> */
        [JsonPropertyName("h-captcha-response")]
        public string? HCaptchaResponse { get { return this.HCaptchaResponseOption; } set { this.HCaptchaResponseOption = new(value); } }

        /// <summary>
        /// Used to track the state of SecurityAnswer
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, string>?> SecurityAnswerOption { get; private set; }

        /// <summary>
        /// The security answers which is set for the User, this will be used when the User is blocked for the security question.
        /// </summary>
        /// <value>The security answers which is set for the User, this will be used when the User is blocked for the security question.</value>
        [JsonPropertyName("SecurityAnswer")]
        public Dictionary<string, string>? SecurityAnswer { get { return this.SecurityAnswerOption; } set { this.SecurityAnswerOption = new(value); } }

        /// <summary>
        /// Used to track the state of WelcomeEmailTemplate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> WelcomeEmailTemplateOption { get; private set; }

        /// <summary>
        /// The template for the welcome Email.
        /// </summary>
        /// <value>The template for the welcome Email.</value>
        /* <example>WelcomeTemplate</example> */
        [JsonPropertyName("WelcomeEmailTemplate")]
        public string? WelcomeEmailTemplate { get { return this.WelcomeEmailTemplateOption; } set { this.WelcomeEmailTemplateOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PasswordLessUserNameOTPModel {\n");
            sb.Append("  Otp: ").Append(Otp).Append("\n");
            sb.Append("  UserName: ").Append(UserName).Append("\n");
            sb.Append("  GRecaptchaResponse: ").Append(GRecaptchaResponse).Append("\n");
            sb.Append("  QqCaptchaTicket: ").Append(QqCaptchaTicket).Append("\n");
            sb.Append("  QqCaptchaRandstr: ").Append(QqCaptchaRandstr).Append("\n");
            sb.Append("  HCaptchaResponse: ").Append(HCaptchaResponse).Append("\n");
            sb.Append("  SecurityAnswer: ").Append(SecurityAnswer).Append("\n");
            sb.Append("  WelcomeEmailTemplate: ").Append(WelcomeEmailTemplate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PasswordLessUserNameOTPModel" />
    /// </summary>
    public class PasswordLessUserNameOTPModelJsonConverter : JsonConverter<PasswordLessUserNameOTPModel>
    {
        /// <summary>
        /// Deserializes json to <see cref="PasswordLessUserNameOTPModel" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PasswordLessUserNameOTPModel Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> otp = default;
            Option<string?> userName = default;
            Option<string?> gRecaptchaResponse = default;
            Option<string?> qqCaptchaTicket = default;
            Option<string?> qqCaptchaRandstr = default;
            Option<string?> hCaptchaResponse = default;
            Option<Dictionary<string, string>?> securityAnswer = default;
            Option<string?> welcomeEmailTemplate = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "Otp":
                            otp = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "UserName":
                            userName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "g-recaptcha-response":
                            gRecaptchaResponse = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "qq_captcha_ticket":
                            qqCaptchaTicket = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "qq_captcha_randstr":
                            qqCaptchaRandstr = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "h-captcha-response":
                            hCaptchaResponse = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "SecurityAnswer":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                securityAnswer = new Option<Dictionary<string, string>?>(JsonSerializer.Deserialize<Dictionary<string, string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "WelcomeEmailTemplate":
                            welcomeEmailTemplate = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!otp.IsSet)
                throw new ArgumentException("Property is required for class PasswordLessUserNameOTPModel.", nameof(otp));

            if (!userName.IsSet)
                throw new ArgumentException("Property is required for class PasswordLessUserNameOTPModel.", nameof(userName));

            if (otp.IsSet && otp.Value == null)
                throw new ArgumentNullException(nameof(otp), "Property is not nullable for class PasswordLessUserNameOTPModel.");

            if (userName.IsSet && userName.Value == null)
                throw new ArgumentNullException(nameof(userName), "Property is not nullable for class PasswordLessUserNameOTPModel.");

            if (welcomeEmailTemplate.IsSet && welcomeEmailTemplate.Value == null)
                throw new ArgumentNullException(nameof(welcomeEmailTemplate), "Property is not nullable for class PasswordLessUserNameOTPModel.");

            return new PasswordLessUserNameOTPModel(otp.Value!, userName.Value!, gRecaptchaResponse, qqCaptchaTicket, qqCaptchaRandstr, hCaptchaResponse, securityAnswer, welcomeEmailTemplate);
        }

        /// <summary>
        /// Serializes a <see cref="PasswordLessUserNameOTPModel" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="passwordLessUserNameOTPModel"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PasswordLessUserNameOTPModel passwordLessUserNameOTPModel, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, passwordLessUserNameOTPModel, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PasswordLessUserNameOTPModel" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="passwordLessUserNameOTPModel"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PasswordLessUserNameOTPModel passwordLessUserNameOTPModel, JsonSerializerOptions jsonSerializerOptions)
        {
            if (passwordLessUserNameOTPModel.Otp == null)
                throw new ArgumentNullException(nameof(passwordLessUserNameOTPModel.Otp), "Property is required for class PasswordLessUserNameOTPModel.");

            if (passwordLessUserNameOTPModel.UserName == null)
                throw new ArgumentNullException(nameof(passwordLessUserNameOTPModel.UserName), "Property is required for class PasswordLessUserNameOTPModel.");

            if (passwordLessUserNameOTPModel.WelcomeEmailTemplateOption.IsSet && passwordLessUserNameOTPModel.WelcomeEmailTemplate == null)
                throw new ArgumentNullException(nameof(passwordLessUserNameOTPModel.WelcomeEmailTemplate), "Property is required for class PasswordLessUserNameOTPModel.");

            writer.WriteString("Otp", passwordLessUserNameOTPModel.Otp);

            writer.WriteString("UserName", passwordLessUserNameOTPModel.UserName);

            if (passwordLessUserNameOTPModel.GRecaptchaResponseOption.IsSet)
                if (passwordLessUserNameOTPModel.GRecaptchaResponseOption.Value != null)
                    writer.WriteString("g-recaptcha-response", passwordLessUserNameOTPModel.GRecaptchaResponse);
                else
                    writer.WriteNull("g-recaptcha-response");

            if (passwordLessUserNameOTPModel.QqCaptchaTicketOption.IsSet)
                if (passwordLessUserNameOTPModel.QqCaptchaTicketOption.Value != null)
                    writer.WriteString("qq_captcha_ticket", passwordLessUserNameOTPModel.QqCaptchaTicket);
                else
                    writer.WriteNull("qq_captcha_ticket");

            if (passwordLessUserNameOTPModel.QqCaptchaRandstrOption.IsSet)
                if (passwordLessUserNameOTPModel.QqCaptchaRandstrOption.Value != null)
                    writer.WriteString("qq_captcha_randstr", passwordLessUserNameOTPModel.QqCaptchaRandstr);
                else
                    writer.WriteNull("qq_captcha_randstr");

            if (passwordLessUserNameOTPModel.HCaptchaResponseOption.IsSet)
                if (passwordLessUserNameOTPModel.HCaptchaResponseOption.Value != null)
                    writer.WriteString("h-captcha-response", passwordLessUserNameOTPModel.HCaptchaResponse);
                else
                    writer.WriteNull("h-captcha-response");

            if (passwordLessUserNameOTPModel.SecurityAnswerOption.IsSet)
                if (passwordLessUserNameOTPModel.SecurityAnswerOption.Value != null)
                {
                    writer.WritePropertyName("SecurityAnswer");
                    JsonSerializer.Serialize(writer, passwordLessUserNameOTPModel.SecurityAnswer, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("SecurityAnswer");
            if (passwordLessUserNameOTPModel.WelcomeEmailTemplateOption.IsSet)
                writer.WriteString("WelcomeEmailTemplate", passwordLessUserNameOTPModel.WelcomeEmailTemplate);
        }
    }
}
