// <auto-generated>
/*
 * LoginRadius API
 *
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LoginRadius.Sdk.Internal.OpenApi.Client;

namespace LoginRadius.Sdk.Internal.OpenApi.Model
{
    /// <summary>
    /// ProfileSuggestionsCompaniesToFollowInner
    /// </summary>
    public partial class ProfileSuggestionsCompaniesToFollowInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProfileSuggestionsCompaniesToFollowInner" /> class.
        /// </summary>
        /// <param name="id">The unique identifier.</param>
        /// <param name="name">The name of the company.</param>
        [JsonConstructor]
        public ProfileSuggestionsCompaniesToFollowInner(Option<string?> id = default, Option<string?> name = default)
        {
            IdOption = id;
            NameOption = name;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IdOption { get; private set; }

        /// <summary>
        /// The unique identifier.
        /// </summary>
        /// <value>The unique identifier.</value>
        /* <example>company_12345</example> */
        [JsonPropertyName("Id")]
        public string? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// The name of the company.
        /// </summary>
        /// <value>The name of the company.</value>
        /* <example>Tech Corp</example> */
        [JsonPropertyName("Name")]
        public string? Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProfileSuggestionsCompaniesToFollowInner {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ProfileSuggestionsCompaniesToFollowInner" />
    /// </summary>
    public class ProfileSuggestionsCompaniesToFollowInnerJsonConverter : JsonConverter<ProfileSuggestionsCompaniesToFollowInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="ProfileSuggestionsCompaniesToFollowInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ProfileSuggestionsCompaniesToFollowInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<string?> name = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "Id":
                            id = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "Name":
                            name = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            return new ProfileSuggestionsCompaniesToFollowInner(id, name);
        }

        /// <summary>
        /// Serializes a <see cref="ProfileSuggestionsCompaniesToFollowInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="profileSuggestionsCompaniesToFollowInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ProfileSuggestionsCompaniesToFollowInner profileSuggestionsCompaniesToFollowInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, profileSuggestionsCompaniesToFollowInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ProfileSuggestionsCompaniesToFollowInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="profileSuggestionsCompaniesToFollowInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ProfileSuggestionsCompaniesToFollowInner profileSuggestionsCompaniesToFollowInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (profileSuggestionsCompaniesToFollowInner.IdOption.IsSet)
                if (profileSuggestionsCompaniesToFollowInner.IdOption.Value != null)
                    writer.WriteString("Id", profileSuggestionsCompaniesToFollowInner.Id);
                else
                    writer.WriteNull("Id");

            if (profileSuggestionsCompaniesToFollowInner.NameOption.IsSet)
                if (profileSuggestionsCompaniesToFollowInner.NameOption.Value != null)
                    writer.WriteString("Name", profileSuggestionsCompaniesToFollowInner.Name);
                else
                    writer.WriteNull("Name");
        }
    }
}
