// <auto-generated>
/*
 * LoginRadius API
 *
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LoginRadius.Sdk.Internal.OpenApi.Client;

namespace LoginRadius.Sdk.Internal.OpenApi.Model
{
    /// <summary>
    /// ProfileRequestModelIMAccountsInner
    /// </summary>
    public partial class ProfileRequestModelIMAccountsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProfileRequestModelIMAccountsInner" /> class.
        /// </summary>
        /// <param name="accountType">accountType</param>
        /// <param name="accountName">accountName</param>
        [JsonConstructor]
        public ProfileRequestModelIMAccountsInner(Option<string?> accountType = default, Option<string?> accountName = default)
        {
            AccountTypeOption = accountType;
            AccountNameOption = accountName;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of AccountType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AccountTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets AccountType
        /// </summary>
        /* <example>Skype</example> */
        [JsonPropertyName("AccountType")]
        public string? AccountType { get { return this.AccountTypeOption; } set { this.AccountTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of AccountName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AccountNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets AccountName
        /// </summary>
        /* <example>john.doe.123</example> */
        [JsonPropertyName("AccountName")]
        public string? AccountName { get { return this.AccountNameOption; } set { this.AccountNameOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProfileRequestModelIMAccountsInner {\n");
            sb.Append("  AccountType: ").Append(AccountType).Append("\n");
            sb.Append("  AccountName: ").Append(AccountName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ProfileRequestModelIMAccountsInner" />
    /// </summary>
    public class ProfileRequestModelIMAccountsInnerJsonConverter : JsonConverter<ProfileRequestModelIMAccountsInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="ProfileRequestModelIMAccountsInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ProfileRequestModelIMAccountsInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> accountType = default;
            Option<string?> accountName = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "AccountType":
                            accountType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "AccountName":
                            accountName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (accountType.IsSet && accountType.Value == null)
                throw new ArgumentNullException(nameof(accountType), "Property is not nullable for class ProfileRequestModelIMAccountsInner.");

            if (accountName.IsSet && accountName.Value == null)
                throw new ArgumentNullException(nameof(accountName), "Property is not nullable for class ProfileRequestModelIMAccountsInner.");

            return new ProfileRequestModelIMAccountsInner(accountType, accountName);
        }

        /// <summary>
        /// Serializes a <see cref="ProfileRequestModelIMAccountsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="profileRequestModelIMAccountsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ProfileRequestModelIMAccountsInner profileRequestModelIMAccountsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, profileRequestModelIMAccountsInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ProfileRequestModelIMAccountsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="profileRequestModelIMAccountsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ProfileRequestModelIMAccountsInner profileRequestModelIMAccountsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (profileRequestModelIMAccountsInner.AccountTypeOption.IsSet && profileRequestModelIMAccountsInner.AccountType == null)
                throw new ArgumentNullException(nameof(profileRequestModelIMAccountsInner.AccountType), "Property is required for class ProfileRequestModelIMAccountsInner.");

            if (profileRequestModelIMAccountsInner.AccountNameOption.IsSet && profileRequestModelIMAccountsInner.AccountName == null)
                throw new ArgumentNullException(nameof(profileRequestModelIMAccountsInner.AccountName), "Property is required for class ProfileRequestModelIMAccountsInner.");

            if (profileRequestModelIMAccountsInner.AccountTypeOption.IsSet)
                writer.WriteString("AccountType", profileRequestModelIMAccountsInner.AccountType);

            if (profileRequestModelIMAccountsInner.AccountNameOption.IsSet)
                writer.WriteString("AccountName", profileRequestModelIMAccountsInner.AccountName);
        }
    }
}
