// <auto-generated>
/*
 * LoginRadius API
 *
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LoginRadius.Sdk.Internal.OpenApi.Client;

namespace LoginRadius.Sdk.Internal.OpenApi.Model
{
    /// <summary>
    /// ProfileRequestModelRecommendationsReceivedInner
    /// </summary>
    public partial class ProfileRequestModelRecommendationsReceivedInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProfileRequestModelRecommendationsReceivedInner" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="recommender">recommender</param>
        /// <param name="recommendationText">recommendationText</param>
        /// <param name="recommendationType">recommendationType</param>
        [JsonConstructor]
        public ProfileRequestModelRecommendationsReceivedInner(Option<string?> id = default, Option<string?> recommender = default, Option<string?> recommendationText = default, Option<string?> recommendationType = default)
        {
            IdOption = id;
            RecommenderOption = recommender;
            RecommendationTextOption = recommendationText;
            RecommendationTypeOption = recommendationType;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        /* <example>rec_456</example> */
        [JsonPropertyName("Id")]
        public string? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Recommender
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RecommenderOption { get; private set; }

        /// <summary>
        /// Gets or Sets Recommender
        /// </summary>
        /* <example>Jane Smith</example> */
        [JsonPropertyName("Recommender")]
        public string? Recommender { get { return this.RecommenderOption; } set { this.RecommenderOption = new(value); } }

        /// <summary>
        /// Used to track the state of RecommendationText
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RecommendationTextOption { get; private set; }

        /// <summary>
        /// Gets or Sets RecommendationText
        /// </summary>
        /* <example>John is an exceptional developer with great leadership skills</example> */
        [JsonPropertyName("RecommendationText")]
        public string? RecommendationText { get { return this.RecommendationTextOption; } set { this.RecommendationTextOption = new(value); } }

        /// <summary>
        /// Used to track the state of RecommendationType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RecommendationTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets RecommendationType
        /// </summary>
        /* <example>Professional</example> */
        [JsonPropertyName("RecommendationType")]
        public string? RecommendationType { get { return this.RecommendationTypeOption; } set { this.RecommendationTypeOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProfileRequestModelRecommendationsReceivedInner {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Recommender: ").Append(Recommender).Append("\n");
            sb.Append("  RecommendationText: ").Append(RecommendationText).Append("\n");
            sb.Append("  RecommendationType: ").Append(RecommendationType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ProfileRequestModelRecommendationsReceivedInner" />
    /// </summary>
    public class ProfileRequestModelRecommendationsReceivedInnerJsonConverter : JsonConverter<ProfileRequestModelRecommendationsReceivedInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="ProfileRequestModelRecommendationsReceivedInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ProfileRequestModelRecommendationsReceivedInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<string?> recommender = default;
            Option<string?> recommendationText = default;
            Option<string?> recommendationType = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "Id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "Recommender":
                            recommender = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "RecommendationText":
                            recommendationText = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "RecommendationType":
                            recommendationType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class ProfileRequestModelRecommendationsReceivedInner.");

            if (recommender.IsSet && recommender.Value == null)
                throw new ArgumentNullException(nameof(recommender), "Property is not nullable for class ProfileRequestModelRecommendationsReceivedInner.");

            if (recommendationText.IsSet && recommendationText.Value == null)
                throw new ArgumentNullException(nameof(recommendationText), "Property is not nullable for class ProfileRequestModelRecommendationsReceivedInner.");

            if (recommendationType.IsSet && recommendationType.Value == null)
                throw new ArgumentNullException(nameof(recommendationType), "Property is not nullable for class ProfileRequestModelRecommendationsReceivedInner.");

            return new ProfileRequestModelRecommendationsReceivedInner(id, recommender, recommendationText, recommendationType);
        }

        /// <summary>
        /// Serializes a <see cref="ProfileRequestModelRecommendationsReceivedInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="profileRequestModelRecommendationsReceivedInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ProfileRequestModelRecommendationsReceivedInner profileRequestModelRecommendationsReceivedInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, profileRequestModelRecommendationsReceivedInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ProfileRequestModelRecommendationsReceivedInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="profileRequestModelRecommendationsReceivedInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ProfileRequestModelRecommendationsReceivedInner profileRequestModelRecommendationsReceivedInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (profileRequestModelRecommendationsReceivedInner.IdOption.IsSet && profileRequestModelRecommendationsReceivedInner.Id == null)
                throw new ArgumentNullException(nameof(profileRequestModelRecommendationsReceivedInner.Id), "Property is required for class ProfileRequestModelRecommendationsReceivedInner.");

            if (profileRequestModelRecommendationsReceivedInner.RecommenderOption.IsSet && profileRequestModelRecommendationsReceivedInner.Recommender == null)
                throw new ArgumentNullException(nameof(profileRequestModelRecommendationsReceivedInner.Recommender), "Property is required for class ProfileRequestModelRecommendationsReceivedInner.");

            if (profileRequestModelRecommendationsReceivedInner.RecommendationTextOption.IsSet && profileRequestModelRecommendationsReceivedInner.RecommendationText == null)
                throw new ArgumentNullException(nameof(profileRequestModelRecommendationsReceivedInner.RecommendationText), "Property is required for class ProfileRequestModelRecommendationsReceivedInner.");

            if (profileRequestModelRecommendationsReceivedInner.RecommendationTypeOption.IsSet && profileRequestModelRecommendationsReceivedInner.RecommendationType == null)
                throw new ArgumentNullException(nameof(profileRequestModelRecommendationsReceivedInner.RecommendationType), "Property is required for class ProfileRequestModelRecommendationsReceivedInner.");

            if (profileRequestModelRecommendationsReceivedInner.IdOption.IsSet)
                writer.WriteString("Id", profileRequestModelRecommendationsReceivedInner.Id);

            if (profileRequestModelRecommendationsReceivedInner.RecommenderOption.IsSet)
                writer.WriteString("Recommender", profileRequestModelRecommendationsReceivedInner.Recommender);

            if (profileRequestModelRecommendationsReceivedInner.RecommendationTextOption.IsSet)
                writer.WriteString("RecommendationText", profileRequestModelRecommendationsReceivedInner.RecommendationText);

            if (profileRequestModelRecommendationsReceivedInner.RecommendationTypeOption.IsSet)
                writer.WriteString("RecommendationType", profileRequestModelRecommendationsReceivedInner.RecommendationType);
        }
    }
}
