// <auto-generated>
/*
 * LoginRadius API
 *
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LoginRadius.Sdk.Internal.OpenApi.Client;

namespace LoginRadius.Sdk.Internal.OpenApi.Model
{
    /// <summary>
    /// QueryRule
    /// </summary>
    public partial class QueryRule : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QueryRule" /> class.
        /// </summary>
        /// <param name="group">group</param>
        /// <param name="name">Name of the field to query.</param>
        /// <param name="operator">Operator for the query (e.g., &#x3D;, !&#x3D;, &gt;, &lt;).</param>
        /// <param name="value">Value to compare against. Can be string, boolean, or number.</param>
        [JsonConstructor]
        public QueryRule(Option<QueryGroup?> group = default, Option<string?> name = default, Option<string?> @operator = default, Option<Object?> value = default)
        {
            GroupOption = group;
            NameOption = name;
            OperatorOption = @operator;
            ValueOption = value;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Group
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<QueryGroup?> GroupOption { get; private set; }

        /// <summary>
        /// Gets or Sets Group
        /// </summary>
        [JsonPropertyName("group")]
        public QueryGroup? Group { get { return this.GroupOption; } set { this.GroupOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Name of the field to query.
        /// </summary>
        /// <value>Name of the field to query.</value>
        /* <example>status</example> */
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Operator
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OperatorOption { get; private set; }

        /// <summary>
        /// Operator for the query (e.g., &#x3D;, !&#x3D;, &gt;, &lt;).
        /// </summary>
        /// <value>Operator for the query (e.g., &#x3D;, !&#x3D;, &gt;, &lt;).</value>
        /* <example>&#x3D;</example> */
        [JsonPropertyName("operator")]
        public string? Operator { get { return this.OperatorOption; } set { this.OperatorOption = new(value); } }

        /// <summary>
        /// Used to track the state of Value
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> ValueOption { get; private set; }

        /// <summary>
        /// Value to compare against. Can be string, boolean, or number.
        /// </summary>
        /// <value>Value to compare against. Can be string, boolean, or number.</value>
        /* <example>active</example> */
        [JsonPropertyName("value")]
        public Object? Value { get { return this.ValueOption; } set { this.ValueOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class QueryRule {\n");
            sb.Append("  Group: ").Append(Group).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Operator: ").Append(Operator).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="QueryRule" />
    /// </summary>
    public class QueryRuleJsonConverter : JsonConverter<QueryRule>
    {
        /// <summary>
        /// Deserializes json to <see cref="QueryRule" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override QueryRule Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<QueryGroup?> group = default;
            Option<string?> name = default;
            Option<string?> varOperator = default;
            Option<Object?> value = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "group":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                group = new Option<QueryGroup?>(JsonSerializer.Deserialize<QueryGroup>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "operator":
                            varOperator = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "value":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                value = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (group.IsSet && group.Value == null)
                throw new ArgumentNullException(nameof(group), "Property is not nullable for class QueryRule.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class QueryRule.");

            if (varOperator.IsSet && varOperator.Value == null)
                throw new ArgumentNullException(nameof(varOperator), "Property is not nullable for class QueryRule.");

            return new QueryRule(group, name, varOperator, value);
        }

        /// <summary>
        /// Serializes a <see cref="QueryRule" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="queryRule"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, QueryRule queryRule, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, queryRule, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="QueryRule" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="queryRule"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, QueryRule queryRule, JsonSerializerOptions jsonSerializerOptions)
        {
            if (queryRule.GroupOption.IsSet && queryRule.Group == null)
                throw new ArgumentNullException(nameof(queryRule.Group), "Property is required for class QueryRule.");

            if (queryRule.NameOption.IsSet && queryRule.Name == null)
                throw new ArgumentNullException(nameof(queryRule.Name), "Property is required for class QueryRule.");

            if (queryRule.OperatorOption.IsSet && queryRule.Operator == null)
                throw new ArgumentNullException(nameof(queryRule.Operator), "Property is required for class QueryRule.");

            if (queryRule.GroupOption.IsSet)
            {
                writer.WritePropertyName("group");
                JsonSerializer.Serialize(writer, queryRule.Group, jsonSerializerOptions);
            }
            if (queryRule.NameOption.IsSet)
                writer.WriteString("name", queryRule.Name);

            if (queryRule.OperatorOption.IsSet)
                writer.WriteString("operator", queryRule.Operator);

            if (queryRule.ValueOption.IsSet)
                if (queryRule.ValueOption.Value != null)
                {
                    writer.WritePropertyName("value");
                    JsonSerializer.Serialize(writer, queryRule.Value, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("value");
        }
    }
}
