// <auto-generated>
/*
 * LoginRadius API
 *
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LoginRadius.Sdk.Internal.OpenApi.Client;

namespace LoginRadius.Sdk.Internal.OpenApi.Model
{
    /// <summary>
    /// ResetPasswordByEmailOtpCore
    /// </summary>
    public partial class ResetPasswordByEmailOtpCore : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ResetPasswordByEmailOtpCore" /> class.
        /// </summary>
        /// <param name="otp">One-time passcode sent to the User&#39;s Email.</param>
        /// <param name="email">User&#39;s Email address.</param>
        /// <param name="password">The new Password for the Account.</param>
        /// <param name="welcomeemailtemplate">Optional welcome Email template.</param>
        /// <param name="resetPasswordEmailTemplate">Optional reset Password Email template.</param>
        /// <param name="securityAnswer">A map of security question keys and their corresponding answers.</param>
        [JsonConstructor]
        public ResetPasswordByEmailOtpCore(string otp, string email, string password, Option<string?> welcomeemailtemplate = default, Option<string?> resetPasswordEmailTemplate = default, Option<Dictionary<string, string>?> securityAnswer = default)
        {
            Otp = otp;
            Email = email;
            Password = password;
            WelcomeemailtemplateOption = welcomeemailtemplate;
            ResetPasswordEmailTemplateOption = resetPasswordEmailTemplate;
            SecurityAnswerOption = securityAnswer;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// One-time passcode sent to the User&#39;s Email.
        /// </summary>
        /// <value>One-time passcode sent to the User&#39;s Email.</value>
        /* <example>123456</example> */
        [JsonPropertyName("otp")]
        public string Otp { get; set; }

        /// <summary>
        /// User&#39;s Email address.
        /// </summary>
        /// <value>User&#39;s Email address.</value>
        /* <example>user@example.com</example> */
        [JsonPropertyName("email")]
        public string Email { get; set; }

        /// <summary>
        /// The new Password for the Account.
        /// </summary>
        /// <value>The new Password for the Account.</value>
        /* <example>new_secure_password</example> */
        [JsonPropertyName("Password")]
        public string Password { get; set; }

        /// <summary>
        /// Used to track the state of Welcomeemailtemplate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> WelcomeemailtemplateOption { get; private set; }

        /// <summary>
        /// Optional welcome Email template.
        /// </summary>
        /// <value>Optional welcome Email template.</value>
        /* <example>welcome_template</example> */
        [JsonPropertyName("welcomeemailtemplate")]
        public string? Welcomeemailtemplate { get { return this.WelcomeemailtemplateOption; } set { this.WelcomeemailtemplateOption = new(value); } }

        /// <summary>
        /// Used to track the state of ResetPasswordEmailTemplate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ResetPasswordEmailTemplateOption { get; private set; }

        /// <summary>
        /// Optional reset Password Email template.
        /// </summary>
        /// <value>Optional reset Password Email template.</value>
        /* <example>reset_password_template</example> */
        [JsonPropertyName("ResetPasswordEmailTemplate")]
        public string? ResetPasswordEmailTemplate { get { return this.ResetPasswordEmailTemplateOption; } set { this.ResetPasswordEmailTemplateOption = new(value); } }

        /// <summary>
        /// Used to track the state of SecurityAnswer
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, string>?> SecurityAnswerOption { get; private set; }

        /// <summary>
        /// A map of security question keys and their corresponding answers.
        /// </summary>
        /// <value>A map of security question keys and their corresponding answers.</value>
        [JsonPropertyName("SecurityAnswer")]
        public Dictionary<string, string>? SecurityAnswer { get { return this.SecurityAnswerOption; } set { this.SecurityAnswerOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ResetPasswordByEmailOtpCore {\n");
            sb.Append("  Otp: ").Append(Otp).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("  Welcomeemailtemplate: ").Append(Welcomeemailtemplate).Append("\n");
            sb.Append("  ResetPasswordEmailTemplate: ").Append(ResetPasswordEmailTemplate).Append("\n");
            sb.Append("  SecurityAnswer: ").Append(SecurityAnswer).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ResetPasswordByEmailOtpCore" />
    /// </summary>
    public class ResetPasswordByEmailOtpCoreJsonConverter : JsonConverter<ResetPasswordByEmailOtpCore>
    {
        /// <summary>
        /// Deserializes json to <see cref="ResetPasswordByEmailOtpCore" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ResetPasswordByEmailOtpCore Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> otp = default;
            Option<string?> email = default;
            Option<string?> password = default;
            Option<string?> welcomeemailtemplate = default;
            Option<string?> resetPasswordEmailTemplate = default;
            Option<Dictionary<string, string>?> securityAnswer = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "otp":
                            otp = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "email":
                            email = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "Password":
                            password = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "welcomeemailtemplate":
                            welcomeemailtemplate = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "ResetPasswordEmailTemplate":
                            resetPasswordEmailTemplate = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "SecurityAnswer":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                securityAnswer = new Option<Dictionary<string, string>?>(JsonSerializer.Deserialize<Dictionary<string, string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!otp.IsSet)
                throw new ArgumentException("Property is required for class ResetPasswordByEmailOtpCore.", nameof(otp));

            if (!email.IsSet)
                throw new ArgumentException("Property is required for class ResetPasswordByEmailOtpCore.", nameof(email));

            if (!password.IsSet)
                throw new ArgumentException("Property is required for class ResetPasswordByEmailOtpCore.", nameof(password));

            if (otp.IsSet && otp.Value == null)
                throw new ArgumentNullException(nameof(otp), "Property is not nullable for class ResetPasswordByEmailOtpCore.");

            if (email.IsSet && email.Value == null)
                throw new ArgumentNullException(nameof(email), "Property is not nullable for class ResetPasswordByEmailOtpCore.");

            if (password.IsSet && password.Value == null)
                throw new ArgumentNullException(nameof(password), "Property is not nullable for class ResetPasswordByEmailOtpCore.");

            if (welcomeemailtemplate.IsSet && welcomeemailtemplate.Value == null)
                throw new ArgumentNullException(nameof(welcomeemailtemplate), "Property is not nullable for class ResetPasswordByEmailOtpCore.");

            if (resetPasswordEmailTemplate.IsSet && resetPasswordEmailTemplate.Value == null)
                throw new ArgumentNullException(nameof(resetPasswordEmailTemplate), "Property is not nullable for class ResetPasswordByEmailOtpCore.");

            return new ResetPasswordByEmailOtpCore(otp.Value!, email.Value!, password.Value!, welcomeemailtemplate, resetPasswordEmailTemplate, securityAnswer);
        }

        /// <summary>
        /// Serializes a <see cref="ResetPasswordByEmailOtpCore" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="resetPasswordByEmailOtpCore"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ResetPasswordByEmailOtpCore resetPasswordByEmailOtpCore, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, resetPasswordByEmailOtpCore, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ResetPasswordByEmailOtpCore" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="resetPasswordByEmailOtpCore"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ResetPasswordByEmailOtpCore resetPasswordByEmailOtpCore, JsonSerializerOptions jsonSerializerOptions)
        {
            if (resetPasswordByEmailOtpCore.Otp == null)
                throw new ArgumentNullException(nameof(resetPasswordByEmailOtpCore.Otp), "Property is required for class ResetPasswordByEmailOtpCore.");

            if (resetPasswordByEmailOtpCore.Email == null)
                throw new ArgumentNullException(nameof(resetPasswordByEmailOtpCore.Email), "Property is required for class ResetPasswordByEmailOtpCore.");

            if (resetPasswordByEmailOtpCore.Password == null)
                throw new ArgumentNullException(nameof(resetPasswordByEmailOtpCore.Password), "Property is required for class ResetPasswordByEmailOtpCore.");

            if (resetPasswordByEmailOtpCore.WelcomeemailtemplateOption.IsSet && resetPasswordByEmailOtpCore.Welcomeemailtemplate == null)
                throw new ArgumentNullException(nameof(resetPasswordByEmailOtpCore.Welcomeemailtemplate), "Property is required for class ResetPasswordByEmailOtpCore.");

            if (resetPasswordByEmailOtpCore.ResetPasswordEmailTemplateOption.IsSet && resetPasswordByEmailOtpCore.ResetPasswordEmailTemplate == null)
                throw new ArgumentNullException(nameof(resetPasswordByEmailOtpCore.ResetPasswordEmailTemplate), "Property is required for class ResetPasswordByEmailOtpCore.");

            writer.WriteString("otp", resetPasswordByEmailOtpCore.Otp);

            writer.WriteString("email", resetPasswordByEmailOtpCore.Email);

            writer.WriteString("Password", resetPasswordByEmailOtpCore.Password);

            if (resetPasswordByEmailOtpCore.WelcomeemailtemplateOption.IsSet)
                writer.WriteString("welcomeemailtemplate", resetPasswordByEmailOtpCore.Welcomeemailtemplate);

            if (resetPasswordByEmailOtpCore.ResetPasswordEmailTemplateOption.IsSet)
                writer.WriteString("ResetPasswordEmailTemplate", resetPasswordByEmailOtpCore.ResetPasswordEmailTemplate);

            if (resetPasswordByEmailOtpCore.SecurityAnswerOption.IsSet)
                if (resetPasswordByEmailOtpCore.SecurityAnswerOption.Value != null)
                {
                    writer.WritePropertyName("SecurityAnswer");
                    JsonSerializer.Serialize(writer, resetPasswordByEmailOtpCore.SecurityAnswer, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("SecurityAnswer");
        }
    }
}
