// <auto-generated>
/*
 * LoginRadius API
 *
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LoginRadius.Sdk.Internal.OpenApi.Client;

namespace LoginRadius.Sdk.Internal.OpenApi.Model
{
    /// <summary>
    /// RoleContextResponseModal
    /// </summary>
    public partial class RoleContextResponseModal : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RoleContextResponseModal" /> class.
        /// </summary>
        /// <param name="data">List of Role Contexts.</param>
        [JsonConstructor]
        public RoleContextResponseModal(List<RoleContext> data)
        {
            Data = data;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// List of Role Contexts.
        /// </summary>
        /// <value>List of Role Contexts.</value>
        [JsonPropertyName("Data")]
        public List<RoleContext> Data { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RoleContextResponseModal {\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="RoleContextResponseModal" />
    /// </summary>
    public class RoleContextResponseModalJsonConverter : JsonConverter<RoleContextResponseModal>
    {
        /// <summary>
        /// Deserializes json to <see cref="RoleContextResponseModal" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override RoleContextResponseModal Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<RoleContext>?> data = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "Data":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                data = new Option<List<RoleContext>?>(JsonSerializer.Deserialize<List<RoleContext>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!data.IsSet)
                throw new ArgumentException("Property is required for class RoleContextResponseModal.", nameof(data));

            if (data.IsSet && data.Value == null)
                throw new ArgumentNullException(nameof(data), "Property is not nullable for class RoleContextResponseModal.");

            return new RoleContextResponseModal(data.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="RoleContextResponseModal" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="roleContextResponseModal"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, RoleContextResponseModal roleContextResponseModal, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, roleContextResponseModal, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="RoleContextResponseModal" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="roleContextResponseModal"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, RoleContextResponseModal roleContextResponseModal, JsonSerializerOptions jsonSerializerOptions)
        {
            if (roleContextResponseModal.Data == null)
                throw new ArgumentNullException(nameof(roleContextResponseModal.Data), "Property is required for class RoleContextResponseModal.");

            writer.WritePropertyName("Data");
            JsonSerializer.Serialize(writer, roleContextResponseModal.Data, jsonSerializerOptions);
        }
    }
}
