// <auto-generated>
/*
 * LoginRadius API
 *
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LoginRadius.Sdk.Internal.OpenApi.Client;

namespace LoginRadius.Sdk.Internal.OpenApi.Model
{
    /// <summary>
    /// SecondFactorAuthentication
    /// </summary>
    public partial class SecondFactorAuthentication : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SecondFactorAuthentication" /> class.
        /// </summary>
        /// <param name="googleAuthenticator">googleAuthenticator</param>
        /// <param name="oTPAuthenticator">oTPAuthenticator</param>
        /// <param name="emailOTPAuthenticator">emailOTPAuthenticator</param>
        /// <param name="backUpCodes">backUpCodes</param>
        /// <param name="authenticator">authenticator</param>
        /// <param name="pushAuthenticator">pushAuthenticator</param>
        /// <param name="duoSecurityAuthenticator">duoSecurityAuthenticator</param>
        /// <param name="passkeyAuthenticator">passkeyAuthenticator</param>
        /// <param name="securityQuestionAuthenticator">securityQuestionAuthenticator</param>
        [JsonConstructor]
        public SecondFactorAuthentication(Option<SecondFactorAuthenticator?> googleAuthenticator = default, Option<SecondFactorAuthenticator?> oTPAuthenticator = default, Option<SecondFactorAuthenticator?> emailOTPAuthenticator = default, Option<List<string>?> backUpCodes = default, Option<SecondFactorAuthenticator?> authenticator = default, Option<SecondFactorAuthenticationPushDevice?> pushAuthenticator = default, Option<SecondFactorAuthenticator?> duoSecurityAuthenticator = default, Option<SecondFactorAuthenticationPasskeyCredential?> passkeyAuthenticator = default, Option<SecondFactorAuthenticator?> securityQuestionAuthenticator = default)
        {
            GoogleAuthenticatorOption = googleAuthenticator;
            OTPAuthenticatorOption = oTPAuthenticator;
            EmailOTPAuthenticatorOption = emailOTPAuthenticator;
            BackUpCodesOption = backUpCodes;
            AuthenticatorOption = authenticator;
            PushAuthenticatorOption = pushAuthenticator;
            DuoSecurityAuthenticatorOption = duoSecurityAuthenticator;
            PasskeyAuthenticatorOption = passkeyAuthenticator;
            SecurityQuestionAuthenticatorOption = securityQuestionAuthenticator;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of GoogleAuthenticator
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<SecondFactorAuthenticator?> GoogleAuthenticatorOption { get; private set; }

        /// <summary>
        /// Gets or Sets GoogleAuthenticator
        /// </summary>
        [JsonPropertyName("GoogleAuthenticator")]
        public SecondFactorAuthenticator? GoogleAuthenticator { get { return this.GoogleAuthenticatorOption; } set { this.GoogleAuthenticatorOption = new(value); } }

        /// <summary>
        /// Used to track the state of OTPAuthenticator
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<SecondFactorAuthenticator?> OTPAuthenticatorOption { get; private set; }

        /// <summary>
        /// Gets or Sets OTPAuthenticator
        /// </summary>
        [JsonPropertyName("OTPAuthenticator")]
        public SecondFactorAuthenticator? OTPAuthenticator { get { return this.OTPAuthenticatorOption; } set { this.OTPAuthenticatorOption = new(value); } }

        /// <summary>
        /// Used to track the state of EmailOTPAuthenticator
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<SecondFactorAuthenticator?> EmailOTPAuthenticatorOption { get; private set; }

        /// <summary>
        /// Gets or Sets EmailOTPAuthenticator
        /// </summary>
        [JsonPropertyName("EmailOTPAuthenticator")]
        public SecondFactorAuthenticator? EmailOTPAuthenticator { get { return this.EmailOTPAuthenticatorOption; } set { this.EmailOTPAuthenticatorOption = new(value); } }

        /// <summary>
        /// Used to track the state of BackUpCodes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> BackUpCodesOption { get; private set; }

        /// <summary>
        /// Gets or Sets BackUpCodes
        /// </summary>
        /* <example>[123456, 654321, 789012]</example> */
        [JsonPropertyName("BackUpCodes")]
        public List<string>? BackUpCodes { get { return this.BackUpCodesOption; } set { this.BackUpCodesOption = new(value); } }

        /// <summary>
        /// Used to track the state of Authenticator
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<SecondFactorAuthenticator?> AuthenticatorOption { get; private set; }

        /// <summary>
        /// Gets or Sets Authenticator
        /// </summary>
        [JsonPropertyName("Authenticator")]
        public SecondFactorAuthenticator? Authenticator { get { return this.AuthenticatorOption; } set { this.AuthenticatorOption = new(value); } }

        /// <summary>
        /// Used to track the state of PushAuthenticator
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<SecondFactorAuthenticationPushDevice?> PushAuthenticatorOption { get; private set; }

        /// <summary>
        /// Gets or Sets PushAuthenticator
        /// </summary>
        [JsonPropertyName("PushAuthenticator")]
        public SecondFactorAuthenticationPushDevice? PushAuthenticator { get { return this.PushAuthenticatorOption; } set { this.PushAuthenticatorOption = new(value); } }

        /// <summary>
        /// Used to track the state of DuoSecurityAuthenticator
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<SecondFactorAuthenticator?> DuoSecurityAuthenticatorOption { get; private set; }

        /// <summary>
        /// Gets or Sets DuoSecurityAuthenticator
        /// </summary>
        [JsonPropertyName("DuoSecurityAuthenticator")]
        public SecondFactorAuthenticator? DuoSecurityAuthenticator { get { return this.DuoSecurityAuthenticatorOption; } set { this.DuoSecurityAuthenticatorOption = new(value); } }

        /// <summary>
        /// Used to track the state of PasskeyAuthenticator
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<SecondFactorAuthenticationPasskeyCredential?> PasskeyAuthenticatorOption { get; private set; }

        /// <summary>
        /// Gets or Sets PasskeyAuthenticator
        /// </summary>
        [JsonPropertyName("PasskeyAuthenticator")]
        public SecondFactorAuthenticationPasskeyCredential? PasskeyAuthenticator { get { return this.PasskeyAuthenticatorOption; } set { this.PasskeyAuthenticatorOption = new(value); } }

        /// <summary>
        /// Used to track the state of SecurityQuestionAuthenticator
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<SecondFactorAuthenticator?> SecurityQuestionAuthenticatorOption { get; private set; }

        /// <summary>
        /// Gets or Sets SecurityQuestionAuthenticator
        /// </summary>
        [JsonPropertyName("SecurityQuestionAuthenticator")]
        public SecondFactorAuthenticator? SecurityQuestionAuthenticator { get { return this.SecurityQuestionAuthenticatorOption; } set { this.SecurityQuestionAuthenticatorOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SecondFactorAuthentication {\n");
            sb.Append("  GoogleAuthenticator: ").Append(GoogleAuthenticator).Append("\n");
            sb.Append("  OTPAuthenticator: ").Append(OTPAuthenticator).Append("\n");
            sb.Append("  EmailOTPAuthenticator: ").Append(EmailOTPAuthenticator).Append("\n");
            sb.Append("  BackUpCodes: ").Append(BackUpCodes).Append("\n");
            sb.Append("  Authenticator: ").Append(Authenticator).Append("\n");
            sb.Append("  PushAuthenticator: ").Append(PushAuthenticator).Append("\n");
            sb.Append("  DuoSecurityAuthenticator: ").Append(DuoSecurityAuthenticator).Append("\n");
            sb.Append("  PasskeyAuthenticator: ").Append(PasskeyAuthenticator).Append("\n");
            sb.Append("  SecurityQuestionAuthenticator: ").Append(SecurityQuestionAuthenticator).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SecondFactorAuthentication" />
    /// </summary>
    public class SecondFactorAuthenticationJsonConverter : JsonConverter<SecondFactorAuthentication>
    {
        /// <summary>
        /// Deserializes json to <see cref="SecondFactorAuthentication" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SecondFactorAuthentication Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<SecondFactorAuthenticator?> googleAuthenticator = default;
            Option<SecondFactorAuthenticator?> oTPAuthenticator = default;
            Option<SecondFactorAuthenticator?> emailOTPAuthenticator = default;
            Option<List<string>?> backUpCodes = default;
            Option<SecondFactorAuthenticator?> authenticator = default;
            Option<SecondFactorAuthenticationPushDevice?> pushAuthenticator = default;
            Option<SecondFactorAuthenticator?> duoSecurityAuthenticator = default;
            Option<SecondFactorAuthenticationPasskeyCredential?> passkeyAuthenticator = default;
            Option<SecondFactorAuthenticator?> securityQuestionAuthenticator = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "GoogleAuthenticator":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                googleAuthenticator = new Option<SecondFactorAuthenticator?>(JsonSerializer.Deserialize<SecondFactorAuthenticator>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "OTPAuthenticator":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                oTPAuthenticator = new Option<SecondFactorAuthenticator?>(JsonSerializer.Deserialize<SecondFactorAuthenticator>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "EmailOTPAuthenticator":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                emailOTPAuthenticator = new Option<SecondFactorAuthenticator?>(JsonSerializer.Deserialize<SecondFactorAuthenticator>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "BackUpCodes":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                backUpCodes = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "Authenticator":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                authenticator = new Option<SecondFactorAuthenticator?>(JsonSerializer.Deserialize<SecondFactorAuthenticator>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "PushAuthenticator":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                pushAuthenticator = new Option<SecondFactorAuthenticationPushDevice?>(JsonSerializer.Deserialize<SecondFactorAuthenticationPushDevice>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "DuoSecurityAuthenticator":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                duoSecurityAuthenticator = new Option<SecondFactorAuthenticator?>(JsonSerializer.Deserialize<SecondFactorAuthenticator>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "PasskeyAuthenticator":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                passkeyAuthenticator = new Option<SecondFactorAuthenticationPasskeyCredential?>(JsonSerializer.Deserialize<SecondFactorAuthenticationPasskeyCredential>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "SecurityQuestionAuthenticator":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                securityQuestionAuthenticator = new Option<SecondFactorAuthenticator?>(JsonSerializer.Deserialize<SecondFactorAuthenticator>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (googleAuthenticator.IsSet && googleAuthenticator.Value == null)
                throw new ArgumentNullException(nameof(googleAuthenticator), "Property is not nullable for class SecondFactorAuthentication.");

            if (oTPAuthenticator.IsSet && oTPAuthenticator.Value == null)
                throw new ArgumentNullException(nameof(oTPAuthenticator), "Property is not nullable for class SecondFactorAuthentication.");

            if (emailOTPAuthenticator.IsSet && emailOTPAuthenticator.Value == null)
                throw new ArgumentNullException(nameof(emailOTPAuthenticator), "Property is not nullable for class SecondFactorAuthentication.");

            if (backUpCodes.IsSet && backUpCodes.Value == null)
                throw new ArgumentNullException(nameof(backUpCodes), "Property is not nullable for class SecondFactorAuthentication.");

            if (authenticator.IsSet && authenticator.Value == null)
                throw new ArgumentNullException(nameof(authenticator), "Property is not nullable for class SecondFactorAuthentication.");

            if (pushAuthenticator.IsSet && pushAuthenticator.Value == null)
                throw new ArgumentNullException(nameof(pushAuthenticator), "Property is not nullable for class SecondFactorAuthentication.");

            if (duoSecurityAuthenticator.IsSet && duoSecurityAuthenticator.Value == null)
                throw new ArgumentNullException(nameof(duoSecurityAuthenticator), "Property is not nullable for class SecondFactorAuthentication.");

            if (passkeyAuthenticator.IsSet && passkeyAuthenticator.Value == null)
                throw new ArgumentNullException(nameof(passkeyAuthenticator), "Property is not nullable for class SecondFactorAuthentication.");

            if (securityQuestionAuthenticator.IsSet && securityQuestionAuthenticator.Value == null)
                throw new ArgumentNullException(nameof(securityQuestionAuthenticator), "Property is not nullable for class SecondFactorAuthentication.");

            return new SecondFactorAuthentication(googleAuthenticator, oTPAuthenticator, emailOTPAuthenticator, backUpCodes, authenticator, pushAuthenticator, duoSecurityAuthenticator, passkeyAuthenticator, securityQuestionAuthenticator);
        }

        /// <summary>
        /// Serializes a <see cref="SecondFactorAuthentication" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="secondFactorAuthentication"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SecondFactorAuthentication secondFactorAuthentication, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, secondFactorAuthentication, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SecondFactorAuthentication" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="secondFactorAuthentication"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SecondFactorAuthentication secondFactorAuthentication, JsonSerializerOptions jsonSerializerOptions)
        {
            if (secondFactorAuthentication.GoogleAuthenticatorOption.IsSet && secondFactorAuthentication.GoogleAuthenticator == null)
                throw new ArgumentNullException(nameof(secondFactorAuthentication.GoogleAuthenticator), "Property is required for class SecondFactorAuthentication.");

            if (secondFactorAuthentication.OTPAuthenticatorOption.IsSet && secondFactorAuthentication.OTPAuthenticator == null)
                throw new ArgumentNullException(nameof(secondFactorAuthentication.OTPAuthenticator), "Property is required for class SecondFactorAuthentication.");

            if (secondFactorAuthentication.EmailOTPAuthenticatorOption.IsSet && secondFactorAuthentication.EmailOTPAuthenticator == null)
                throw new ArgumentNullException(nameof(secondFactorAuthentication.EmailOTPAuthenticator), "Property is required for class SecondFactorAuthentication.");

            if (secondFactorAuthentication.BackUpCodesOption.IsSet && secondFactorAuthentication.BackUpCodes == null)
                throw new ArgumentNullException(nameof(secondFactorAuthentication.BackUpCodes), "Property is required for class SecondFactorAuthentication.");

            if (secondFactorAuthentication.AuthenticatorOption.IsSet && secondFactorAuthentication.Authenticator == null)
                throw new ArgumentNullException(nameof(secondFactorAuthentication.Authenticator), "Property is required for class SecondFactorAuthentication.");

            if (secondFactorAuthentication.PushAuthenticatorOption.IsSet && secondFactorAuthentication.PushAuthenticator == null)
                throw new ArgumentNullException(nameof(secondFactorAuthentication.PushAuthenticator), "Property is required for class SecondFactorAuthentication.");

            if (secondFactorAuthentication.DuoSecurityAuthenticatorOption.IsSet && secondFactorAuthentication.DuoSecurityAuthenticator == null)
                throw new ArgumentNullException(nameof(secondFactorAuthentication.DuoSecurityAuthenticator), "Property is required for class SecondFactorAuthentication.");

            if (secondFactorAuthentication.PasskeyAuthenticatorOption.IsSet && secondFactorAuthentication.PasskeyAuthenticator == null)
                throw new ArgumentNullException(nameof(secondFactorAuthentication.PasskeyAuthenticator), "Property is required for class SecondFactorAuthentication.");

            if (secondFactorAuthentication.SecurityQuestionAuthenticatorOption.IsSet && secondFactorAuthentication.SecurityQuestionAuthenticator == null)
                throw new ArgumentNullException(nameof(secondFactorAuthentication.SecurityQuestionAuthenticator), "Property is required for class SecondFactorAuthentication.");

            if (secondFactorAuthentication.GoogleAuthenticatorOption.IsSet)
            {
                writer.WritePropertyName("GoogleAuthenticator");
                JsonSerializer.Serialize(writer, secondFactorAuthentication.GoogleAuthenticator, jsonSerializerOptions);
            }
            if (secondFactorAuthentication.OTPAuthenticatorOption.IsSet)
            {
                writer.WritePropertyName("OTPAuthenticator");
                JsonSerializer.Serialize(writer, secondFactorAuthentication.OTPAuthenticator, jsonSerializerOptions);
            }
            if (secondFactorAuthentication.EmailOTPAuthenticatorOption.IsSet)
            {
                writer.WritePropertyName("EmailOTPAuthenticator");
                JsonSerializer.Serialize(writer, secondFactorAuthentication.EmailOTPAuthenticator, jsonSerializerOptions);
            }
            if (secondFactorAuthentication.BackUpCodesOption.IsSet)
            {
                writer.WritePropertyName("BackUpCodes");
                JsonSerializer.Serialize(writer, secondFactorAuthentication.BackUpCodes, jsonSerializerOptions);
            }
            if (secondFactorAuthentication.AuthenticatorOption.IsSet)
            {
                writer.WritePropertyName("Authenticator");
                JsonSerializer.Serialize(writer, secondFactorAuthentication.Authenticator, jsonSerializerOptions);
            }
            if (secondFactorAuthentication.PushAuthenticatorOption.IsSet)
            {
                writer.WritePropertyName("PushAuthenticator");
                JsonSerializer.Serialize(writer, secondFactorAuthentication.PushAuthenticator, jsonSerializerOptions);
            }
            if (secondFactorAuthentication.DuoSecurityAuthenticatorOption.IsSet)
            {
                writer.WritePropertyName("DuoSecurityAuthenticator");
                JsonSerializer.Serialize(writer, secondFactorAuthentication.DuoSecurityAuthenticator, jsonSerializerOptions);
            }
            if (secondFactorAuthentication.PasskeyAuthenticatorOption.IsSet)
            {
                writer.WritePropertyName("PasskeyAuthenticator");
                JsonSerializer.Serialize(writer, secondFactorAuthentication.PasskeyAuthenticator, jsonSerializerOptions);
            }
            if (secondFactorAuthentication.SecurityQuestionAuthenticatorOption.IsSet)
            {
                writer.WritePropertyName("SecurityQuestionAuthenticator");
                JsonSerializer.Serialize(writer, secondFactorAuthentication.SecurityQuestionAuthenticator, jsonSerializerOptions);
            }
        }
    }
}
