// <auto-generated>
/*
 * LoginRadius API
 *
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LoginRadius.Sdk.Internal.OpenApi.Client;

namespace LoginRadius.Sdk.Internal.OpenApi.Model
{
    /// <summary>
    /// SocialIdentityInterestsInner
    /// </summary>
    public partial class SocialIdentityInterestsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SocialIdentityInterestsInner" /> class.
        /// </summary>
        /// <param name="interestType">interestType</param>
        /// <param name="interestName">interestName</param>
        [JsonConstructor]
        public SocialIdentityInterestsInner(Option<string?> interestType = default, Option<string?> interestName = default)
        {
            InterestTypeOption = interestType;
            InterestNameOption = interestName;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of InterestType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> InterestTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets InterestType
        /// </summary>
        /* <example>Professional</example> */
        [JsonPropertyName("InterestType")]
        public string? InterestType { get { return this.InterestTypeOption; } set { this.InterestTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of InterestName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> InterestNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets InterestName
        /// </summary>
        /* <example>Software Architecture</example> */
        [JsonPropertyName("InterestName")]
        public string? InterestName { get { return this.InterestNameOption; } set { this.InterestNameOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SocialIdentityInterestsInner {\n");
            sb.Append("  InterestType: ").Append(InterestType).Append("\n");
            sb.Append("  InterestName: ").Append(InterestName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SocialIdentityInterestsInner" />
    /// </summary>
    public class SocialIdentityInterestsInnerJsonConverter : JsonConverter<SocialIdentityInterestsInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="SocialIdentityInterestsInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SocialIdentityInterestsInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> interestType = default;
            Option<string?> interestName = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "InterestType":
                            interestType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "InterestName":
                            interestName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (interestType.IsSet && interestType.Value == null)
                throw new ArgumentNullException(nameof(interestType), "Property is not nullable for class SocialIdentityInterestsInner.");

            if (interestName.IsSet && interestName.Value == null)
                throw new ArgumentNullException(nameof(interestName), "Property is not nullable for class SocialIdentityInterestsInner.");

            return new SocialIdentityInterestsInner(interestType, interestName);
        }

        /// <summary>
        /// Serializes a <see cref="SocialIdentityInterestsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="socialIdentityInterestsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SocialIdentityInterestsInner socialIdentityInterestsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, socialIdentityInterestsInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SocialIdentityInterestsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="socialIdentityInterestsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SocialIdentityInterestsInner socialIdentityInterestsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (socialIdentityInterestsInner.InterestTypeOption.IsSet && socialIdentityInterestsInner.InterestType == null)
                throw new ArgumentNullException(nameof(socialIdentityInterestsInner.InterestType), "Property is required for class SocialIdentityInterestsInner.");

            if (socialIdentityInterestsInner.InterestNameOption.IsSet && socialIdentityInterestsInner.InterestName == null)
                throw new ArgumentNullException(nameof(socialIdentityInterestsInner.InterestName), "Property is required for class SocialIdentityInterestsInner.");

            if (socialIdentityInterestsInner.InterestTypeOption.IsSet)
                writer.WriteString("InterestType", socialIdentityInterestsInner.InterestType);

            if (socialIdentityInterestsInner.InterestNameOption.IsSet)
                writer.WriteString("InterestName", socialIdentityInterestsInner.InterestName);
        }
    }
}
