// <auto-generated>
/*
 * LoginRadius API
 *
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LoginRadius.Sdk.Internal.OpenApi.Client;

namespace LoginRadius.Sdk.Internal.OpenApi.Model
{
    /// <summary>
    /// WorkflowDataTree
    /// </summary>
    public partial class WorkflowDataTree : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowDataTree" /> class.
        /// </summary>
        /// <param name="entryNodeId">The entry node ID of the tree.</param>
        /// <param name="nodes">nodes</param>
        [JsonConstructor]
        public WorkflowDataTree(Option<string?> entryNodeId = default, Option<Dictionary<string, WorkflowDataTreeNodesValue>?> nodes = default)
        {
            EntryNodeIdOption = entryNodeId;
            NodesOption = nodes;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of EntryNodeId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EntryNodeIdOption { get; private set; }

        /// <summary>
        /// The entry node ID of the tree.
        /// </summary>
        /// <value>The entry node ID of the tree.</value>
        /* <example>start</example> */
        [JsonPropertyName("entryNodeId")]
        public string? EntryNodeId { get { return this.EntryNodeIdOption; } set { this.EntryNodeIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Nodes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, WorkflowDataTreeNodesValue>?> NodesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Nodes
        /// </summary>
        [JsonPropertyName("nodes")]
        public Dictionary<string, WorkflowDataTreeNodesValue>? Nodes { get { return this.NodesOption; } set { this.NodesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkflowDataTree {\n");
            sb.Append("  EntryNodeId: ").Append(EntryNodeId).Append("\n");
            sb.Append("  Nodes: ").Append(Nodes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="WorkflowDataTree" />
    /// </summary>
    public class WorkflowDataTreeJsonConverter : JsonConverter<WorkflowDataTree>
    {
        /// <summary>
        /// Deserializes json to <see cref="WorkflowDataTree" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override WorkflowDataTree Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> entryNodeId = default;
            Option<Dictionary<string, WorkflowDataTreeNodesValue>?> nodes = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "entryNodeId":
                            entryNodeId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "nodes":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                nodes = new Option<Dictionary<string, WorkflowDataTreeNodesValue>?>(JsonSerializer.Deserialize<Dictionary<string, WorkflowDataTreeNodesValue>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (entryNodeId.IsSet && entryNodeId.Value == null)
                throw new ArgumentNullException(nameof(entryNodeId), "Property is not nullable for class WorkflowDataTree.");

            if (nodes.IsSet && nodes.Value == null)
                throw new ArgumentNullException(nameof(nodes), "Property is not nullable for class WorkflowDataTree.");

            return new WorkflowDataTree(entryNodeId, nodes);
        }

        /// <summary>
        /// Serializes a <see cref="WorkflowDataTree" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="workflowDataTree"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, WorkflowDataTree workflowDataTree, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, workflowDataTree, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="WorkflowDataTree" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="workflowDataTree"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, WorkflowDataTree workflowDataTree, JsonSerializerOptions jsonSerializerOptions)
        {
            if (workflowDataTree.EntryNodeIdOption.IsSet && workflowDataTree.EntryNodeId == null)
                throw new ArgumentNullException(nameof(workflowDataTree.EntryNodeId), "Property is required for class WorkflowDataTree.");

            if (workflowDataTree.NodesOption.IsSet && workflowDataTree.Nodes == null)
                throw new ArgumentNullException(nameof(workflowDataTree.Nodes), "Property is required for class WorkflowDataTree.");

            if (workflowDataTree.EntryNodeIdOption.IsSet)
                writer.WriteString("entryNodeId", workflowDataTree.EntryNodeId);

            if (workflowDataTree.NodesOption.IsSet)
            {
                writer.WritePropertyName("nodes");
                JsonSerializer.Serialize(writer, workflowDataTree.Nodes, jsonSerializerOptions);
            }
        }
    }
}
