
      
      
name: Publish LoginRadius SDK on Nuget Package  manager

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build /Source/LoginRadiusSDK.V2/LoginRadiusSDK.V2.csproj --configuration Release 
    - name: Test with dotnet
      run: dotnet test
    - name: Pack with dotnet
      run: dotnet pack /Source/LoginRadiusSDK.V2/LoginRadiusSDK.V2.csproj --output nuget-packages --configuration Release
    - name: Push with dotnet
      run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      
